// Dino data: name, wiki article title, difficulty level (1-5), length in metres.
// Facts are fetched live from the Wikipedia summary API — nothing hardcoded here.
const DINOS = [
  // ── Level 1 – Super Famous ────────────────────────────────────────────────
  { name: "Tyrannosaurus Rex",    wiki: "Tyrannosaurus",        level: 1, length: 12,   period: "Late Cretaceous (68–66 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Triceratops",          wiki: "Triceratops",          level: 1, length: 9,    period: "Late Cretaceous (68–66 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Stegosaurus",          wiki: "Stegosaurus",          level: 1, length: 9,    period: "Late Jurassic (155–150 Ma)",    diet: "Herbivore",   geo: "North America, Europe" },
  { name: "Brachiosaurus",        wiki: "Brachiosaurus",        level: 1, length: 26,   period: "Late Jurassic (154–153 Ma)",    diet: "Herbivore",   geo: "North America, Africa" },
  { name: "Velociraptor",         wiki: "Velociraptor",         level: 1, length: 2,    period: "Late Cretaceous (75–71 Ma)",    diet: "Carnivore",   geo: "Asia"                  },
  { name: "Ankylosaurus",         wiki: "Ankylosaurus",         level: 1, length: 10,   period: "Late Cretaceous (68–66 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Diplodocus",           wiki: "Diplodocus",           level: 1, length: 27,   period: "Late Jurassic (154–152 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Spinosaurus",          wiki: "Spinosaurus",          level: 1, length: 15,   period: "Cretaceous (99–93 Ma)",         diet: "Piscivore",   geo: "North Africa"          },
  { name: "Pteranodon",           wiki: "Pteranodon",           level: 2, length: 1.8,  period: "Late Cretaceous (86–84 Ma)",    diet: "Piscivore",   geo: "North America"         },
  { name: "Apatosaurus",          wiki: "Apatosaurus",          level: 2, length: 23,   period: "Late Jurassic (154–150 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Allosaurus",           wiki: "Allosaurus",           level: 1, length: 12,   period: "Late Jurassic (155–145 Ma)",    diet: "Carnivore",   geo: "North America, Europe" },
  { name: "Iguanodon",            wiki: "Iguanodon",            level: 2, length: 10,   period: "Early Cretaceous (126–113 Ma)", diet: "Herbivore",   geo: "Europe, North America" },

  // ── Level 2 – Well Known ──────────────────────────────────────────────────
  { name: "Parasaurolophus",      wiki: "Parasaurolophus",      level: 2, length: 10,   period: "Late Cretaceous (76–73 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Pachycephalosaurus",   wiki: "Pachycephalosaurus",   level: 2, length: 5,    period: "Late Cretaceous (70–66 Ma)",    diet: "Omnivore",    geo: "North America"         },
  { name: "Carnotaurus",          wiki: "Carnotaurus",          level: 1, length: 9,    period: "Late Cretaceous (72–69 Ma)",    diet: "Carnivore",   geo: "South America"         },
  { name: "Dilophosaurus",        wiki: "Dilophosaurus",        level: 1, length: 6,    period: "Early Jurassic (~193 Ma)",      diet: "Carnivore",   geo: "North America"         },
  { name: "Gallimimus",           wiki: "Gallimimus",           level: 2, length: 6,    period: "Late Cretaceous (~70 Ma)",      diet: "Omnivore",    geo: "Asia"                  },
  { name: "Mosasaurus",           wiki: "Mosasaurus",           level: 1, length: 17,   period: "Late Cretaceous (82–66 Ma)",    diet: "Carnivore",   geo: "Worldwide (oceans)"    },
  { name: "Archaeopteryx",        wiki: "Archaeopteryx",        level: 1, length: 0.5,  period: "Late Jurassic (~150 Ma)",       diet: "Carnivore",   geo: "Europe"                },
  { name: "Edmontosaurus",        wiki: "Edmontosaurus",        level: 2, length: 13,   period: "Late Cretaceous (73–66 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Deinonychus",          wiki: "Deinonychus",          level: 1, length: 3.4,  period: "Early Cretaceous (115–108 Ma)", diet: "Carnivore",   geo: "North America"         },
  { name: "Coelophysis",          wiki: "Coelophysis",          level: 2, length: 3,    period: "Late Triassic (213–203 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Troodon",              wiki: "Troodon",              level: 2, length: 2.4,  period: "Late Cretaceous (77–66 Ma)",    diet: "Omnivore",    geo: "North America"         },
  { name: "Utahraptor",           wiki: "Utahraptor",           level: 2, length: 6,    period: "Early Cretaceous (~126 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Corythosaurus",        wiki: "Corythosaurus",        level: 3, length: 9,    period: "Late Cretaceous (77–75 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Plateosaurus",         wiki: "Plateosaurus",         level: 3, length: 8,    period: "Late Triassic (214–204 Ma)",    diet: "Herbivore",   geo: "Europe"                },

  // ── Level 3 – Intermediate ────────────────────────────────────────────────
  { name: "Baryonyx",             wiki: "Baryonyx",             level: 2, length: 10,   period: "Early Cretaceous (130–125 Ma)", diet: "Piscivore",   geo: "Europe"                },
  { name: "Ceratosaurus",         wiki: "Ceratosaurus",         level: 2, length: 6,    period: "Late Jurassic (153–148 Ma)",    diet: "Carnivore",   geo: "North America, Africa" },
  { name: "Maiasaura",            wiki: "Maiasaura",            level: 3, length: 9,    period: "Late Cretaceous (77–75 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Oviraptor",            wiki: "Oviraptor",            level: 2, length: 2,    period: "Late Cretaceous (75–71 Ma)",    diet: "Omnivore",    geo: "Asia"                  },
  { name: "Carcharodontosaurus",  wiki: "Carcharodontosaurus",  level: 2, length: 13,   period: "Cretaceous (99–94 Ma)",         diet: "Carnivore",   geo: "North Africa"          },
  { name: "Suchomimus",           wiki: "Suchomimus",           level: 3, length: 11,   period: "Early Cretaceous (~112 Ma)",    diet: "Piscivore",   geo: "Africa"                },
  { name: "Kentrosaurus",         wiki: "Kentrosaurus",         level: 3, length: 4.5,  period: "Late Jurassic (156–150 Ma)",    diet: "Herbivore",   geo: "Africa"                },
  { name: "Protoceratops",        wiki: "Protoceratops",        level: 2, length: 1.8,  period: "Late Cretaceous (75–71 Ma)",    diet: "Herbivore",   geo: "Asia"                  },
  { name: "Camarasaurus",         wiki: "Camarasaurus",         level: 3, length: 18,   period: "Late Jurassic (155–145 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Camptosaurus",         wiki: "Camptosaurus",         level: 4, length: 7,    period: "Late Jurassic (155–145 Ma)",    diet: "Herbivore",   geo: "North America, Europe" },
  { name: "Ouranosaurus",         wiki: "Ouranosaurus",         level: 3, length: 8,    period: "Early Cretaceous (~112 Ma)",    diet: "Herbivore",   geo: "Africa"                },
  { name: "Psittacosaurus",       wiki: "Psittacosaurus",       level: 3, length: 2,    period: "Early Cretaceous (126–101 Ma)", diet: "Herbivore",   geo: "Asia"                  },
  { name: "Saurolophus",          wiki: "Saurolophus",          level: 3, length: 9,    period: "Late Cretaceous (70–68 Ma)",    diet: "Herbivore",   geo: "North America, Asia"   },
  { name: "Megaraptor",           wiki: "Megaraptor",           level: 3, length: 8,    period: "Late Cretaceous (~90 Ma)",      diet: "Carnivore",   geo: "South America"         },
  { name: "Concavenator",         wiki: "Concavenator",         level: 3, length: 6,    period: "Early Cretaceous (~130 Ma)",    diet: "Carnivore",   geo: "Europe"                },

  // ── Level 4 – Advanced ────────────────────────────────────────────────────
  { name: "Styracosaurus",        wiki: "Styracosaurus",        level: 2, length: 5.5,  period: "Late Cretaceous (75–74 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Therizinosaurus",      wiki: "Therizinosaurus",      level: 2, length: 10,   period: "Late Cretaceous (~70 Ma)",      diet: "Herbivore",   geo: "Asia"                  },
  { name: "Gorgosaurus",          wiki: "Gorgosaurus",          level: 3, length: 9,    period: "Late Cretaceous (76–74 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Amargasaurus",         wiki: "Amargasaurus",         level: 3, length: 10,   period: "Early Cretaceous (130–125 Ma)", diet: "Herbivore",   geo: "South America"         },
  { name: "Euoplocephalus",       wiki: "Euoplocephalus",       level: 3, length: 6,    period: "Late Cretaceous (76–74 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Pachyrhinosaurus",     wiki: "Pachyrhinosaurus",     level: 3, length: 8,    period: "Late Cretaceous (73–69 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Lambeosaurus",         wiki: "Lambeosaurus",         level: 3, length: 9,    period: "Late Cretaceous (76–75 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Albertosaurus",        wiki: "Albertosaurus",        level: 2, length: 9,    period: "Late Cretaceous (73–70 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Pentaceratops",        wiki: "Pentaceratops",        level: 4, length: 8,    period: "Late Cretaceous (76–73 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Anchiceratops",        wiki: "Anchiceratops",        level: 5, length: 6,    period: "Late Cretaceous (72–71 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Irritator",            wiki: "Irritator",            level: 3, length: 8,    period: "Early Cretaceous (~110 Ma)",    diet: "Piscivore",   geo: "South America"         },
  { name: "Scelidosaurus",        wiki: "Scelidosaurus",        level: 4, length: 4,    period: "Early Jurassic (196–183 Ma)",   diet: "Herbivore",   geo: "Europe"                },
  { name: "Tsintaosaurus",        wiki: "Tsintaosaurus",        level: 4, length: 8,    period: "Late Cretaceous (84–71 Ma)",    diet: "Herbivore",   geo: "Asia"                  },

  // ── Level 5 – Expert ──────────────────────────────────────────────────────
  { name: "Argentinosaurus",      wiki: "Argentinosaurus",      level: 2, length: 35,   period: "Late Cretaceous (96–93 Ma)",    diet: "Herbivore",   geo: "South America"         },
  { name: "Quetzalcoatlus",       wiki: "Quetzalcoatlus",       level: 1, length: 3,    period: "Late Cretaceous (68–66 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Microraptor",          wiki: "Microraptor",          level: 2, length: 0.8,  period: "Early Cretaceous (125–120 Ma)", diet: "Carnivore",   geo: "Asia"                  },
  { name: "Giganotosaurus",       wiki: "Giganotosaurus",       level: 1, length: 13,   period: "Late Cretaceous (99–95 Ma)",    diet: "Carnivore",   geo: "South America"         },
  { name: "Eoraptor",             wiki: "Eoraptor",             level: 3, length: 1,    period: "Late Triassic (~231 Ma)",       diet: "Omnivore",    geo: "South America"         },
  { name: "Sauroposeidon",        wiki: "Sauroposeidon",        level: 3, length: 34,   period: "Early Cretaceous (~110 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Sinosauropteryx",      wiki: "Sinosauropteryx",      level: 3, length: 1,    period: "Early Cretaceous (~125 Ma)",    diet: "Carnivore",   geo: "Asia"                  },
  { name: "Herrerasaurus",        wiki: "Herrerasaurus",        level: 2, length: 4.5,  period: "Late Triassic (~231 Ma)",       diet: "Carnivore",   geo: "South America"         },
  { name: "Dracorex",             wiki: "Dracorex",             level: 5, length: 3,    period: "Late Cretaceous (~66 Ma)",      diet: "Herbivore",   geo: "North America"         },
  { name: "Nothronychus",         wiki: "Nothronychus",         level: 4, length: 4.5,  period: "Late Cretaceous (~91 Ma)",      diet: "Herbivore",   geo: "North America"         },
  { name: "Magyarosaurus",        wiki: "Magyarosaurus",        level: 4, length: 6,    period: "Late Cretaceous (70–66 Ma)",    diet: "Herbivore",   geo: "Europe"                },
  { name: "Abrictosaurus",        wiki: "Abrictosaurus",        level: 5, length: 1.2,  period: "Early Jurassic (200–190 Ma)",   diet: "Herbivore",   geo: "Africa"                },
  { name: "Yinlong",              wiki: "Yinlong",              level: 5, length: 1.2,  period: "Late Jurassic (161–157 Ma)",    diet: "Omnivore",    geo: "Asia"                  },
  { name: "Limusaurus",           wiki: "Limusaurus",           level: 4, length: 1.7,  period: "Late Jurassic (163–145 Ma)",    diet: "Herbivore",   geo: "Asia"                  },

  // ── Added by add-dinos.py — fill in level/length/period/diet/geo ──
  { name: "Kritosaurus", wiki: "Kritosaurus", level: 5, length: 8.5, period: "Late Cretaceous", diet: "Herbivore", geo: "North America" },
  { name: "Hadrosaurus", wiki: "Hadrosaurus", level: 3, length: 8.0, period: "Late Cretaceous", diet: "Herbivore", geo: "North America" },
  { name: "Diabloceratops", wiki: "Diabloceratops", level: 4, length: 5.5, period: "Cretaceous", diet: "Herbivore", geo: "United States" },
  { name: "Cryolophosaurus", wiki: "Cryolophosaurus", level: 3, length: 6.5, period: "Early Jurassic", diet: "Carnivore", geo: "Antarctica" },
  { name: "Charonosaurus", wiki: "Charonosaurus", level: 4, length: 10.0, period: "Cretaceous", diet: "Herbivore", geo: "China" },
  { name: "Nemegtosaurus", wiki: "Nemegtosaurus", level: 5, length: 15.0, period: "Late Cretaceous", diet: "Herbivore", geo: "Mongolia" },
  { name: "Einiosaurus", wiki: "Einiosaurus", level: 4, length: 4.5, period: "Cretaceous", diet: "Herbivore", geo: "India" },
  { name: "Muttaburrasaurus", wiki: "Muttaburrasaurus", level: 3, length: 7.0, period: "Cretaceous", diet: "Herbivore", geo: "Australia" },
  { name: "Afrovenator", wiki: "Afrovenator", level: 4, length: 8.0, period: "Late Jurassic", diet: "Carnivore", geo: "Africa, Tanzania, Niger" },
  { name: "Massospondylus", wiki: "Massospondylus", level: 4, length: 5.0, period: "Early Jurassic", diet: "Herbivore", geo: "South Africa, Argentina, India" },
  { name: "Leaellynasaura", wiki: "Leaellynasaura", level: 4, length: 0.9, period: "Early Cretaceous", diet: "Herbivore", geo: "Australia" },
  { name: "Dacentrurus", wiki: "Dacentrurus", level: 4, length: 8.0, period: "Late Jurassic", diet: "Herbivore", geo: "Europe, England" },
  { name: "Lufengosaurus", wiki: "Lufengosaurus", level: 5, length: 6.0, period: "Early Jurassic", diet: "", geo: "China" },
  { name: "Futalognkosaurus", wiki: "Futalognkosaurus", level: 5, length: 30.0, period: "Cretaceous", diet: "Herbivore", geo: "Argentina" },
  { name: "Tarbosaurus", wiki: "Tarbosaurus", level: 2, length: 12.0, period: "Late Cretaceous", diet: "Carnivore", geo: "Asia, China, Mongolia" },
  { name: "Turiasaurus", wiki: "Turiasaurus", level: 5, length: 30.0, period: "", diet: "Herbivore", geo: "Spain" },
  { name: "Shunosaurus", wiki: "Shunosaurus", level: 4, length: 9.0, period: "Late Jurassic", diet: "Herbivore", geo: "China" },
  { name: "Proceratosaurus", wiki: "Proceratosaurus", level: 4, length: 3.0, period: "Middle Jurassic", diet: "Carnivore", geo: "England" },
  { name: "Omeisaurus", wiki: "Omeisaurus", level: 5, length: 15.0, period: "Late Jurassic", diet: "Herbivore", geo: "China" },
  { name: "Saichania", wiki: "Saichania", level: 4, length: 7.0, period: "Late Cretaceous", diet: "Herbivore", geo: "China, Mongolia" },
  { name: "Scipionyx", wiki: "Scipionyx", level: 4, length: 0.5, period: "Early Cretaceous", diet: "Carnivore", geo: "" },
  { name: "Yi", wiki: "Yi", level: 5, length: 0.4, period: "", diet: "", geo: "" },
  { name: "Citipati", wiki: "Citipati", level: 4, length: 2.5, period: "Late Cretaceous", diet: "", geo: "Asia" },
  { name: "Supersaurus", wiki: "Supersaurus", level: 3, length: 33.0, period: "Late Jurassic", diet: "Herbivore", geo: "North America, Portugal" },
  { name: "Brachylophosaurus", wiki: "Brachylophosaurus", level: 4, length: 9.0, period: "Late Cretaceous", diet: "Herbivore", geo: "North America, Canada" },
  { name: "Europasaurus", wiki: "Europasaurus", level: 4, length: 6.0, period: "Late Jurassic", diet: "Herbivore", geo: "Germany" },
  { name: "Zuniceratops", wiki: "Zuniceratops", level: 5, length: 3.5, period: "Late Cretaceous", diet: "Herbivore", geo: "United States" },
  { name: "Anchiornis", wiki: "Anchiornis", level: 3, length: 0.4, period: "Late Jurassic", diet: "", geo: "China" },
  { name: "Bactrosaurus", wiki: "Bactrosaurus", level: 5, length: 6.0, period: "Late Cretaceous", diet: "Herbivore", geo: "Asia" },
  { name: "Juravenator", wiki: "Juravenator", level: 5, length: 0.75, period: "Late Jurassic", diet: "Carnivore", geo: "Germany" },
  { name: "Struthiomimus", wiki: "Struthiomimus", level: 3, length: 4.3, period: "Late Cretaceous", diet: "Omnivore", geo: "North America" },
  { name: "Mapusaurus", wiki: "Mapusaurus", level: 3, length: 12.0, period: "Late Cretaceous", diet: "", geo: "Argentina" },
  { name: "Zephyrosaurus", wiki: "Zephyrosaurus", level: 5, length: 1.8, period: "Early Cretaceous", diet: "", geo: "" },
  { name: "Thescelosaurus", wiki: "Thescelosaurus", level: 3, length: 3.5, period: "Late Cretaceous", diet: "Herbivore", geo: "North America" },
  { name: "Kosmoceratops", wiki: "Kosmoceratops", level: 4, length: 4.5, period: "Late Cretaceous", diet: "Herbivore", geo: "North America" },
  { name: "Ichthyovenator", wiki: "Ichthyovenator", level: 4, length: 8.0, period: "Early Cretaceous", diet: "Piscivore", geo: "" },
  { name: "Daspletosaurus", wiki: "Daspletosaurus", level: 3, length: 9.0, period: "Late Cretaceous", diet: "Carnivore", geo: "" },
  { name: "Yunnanosaurus", wiki: "Yunnanosaurus", level: 5, length: 7.0, period: "", diet: "Herbivore", geo: "China" },
  { name: "Huayangosaurus", wiki: "Huayangosaurus", level: 5, length: 4.5, period: "Middle Jurassic", diet: "Carnivore", geo: "North America, China" },
  { name: "Sinornithosaurus", wiki: "Sinornithosaurus", level: 4, length: 1.0, period: "Cretaceous", diet: "Carnivore", geo: "China" },
  { name: "Mamenchisaurus", wiki: "Mamenchisaurus", level: 3, length: 26.0, period: "Late Jurassic", diet: "Herbivore", geo: "China" },
  { name: "Falcarius", wiki: "Falcarius", level: 5, length: 4.0, period: "Early Cretaceous", diet: "", geo: "North America" },
  { name: "Xenoceratops", wiki: "Xenoceratops", level: 5, length: 6.0, period: "Late Cretaceous", diet: "", geo: "Canada" },
  { name: "Minmi", wiki: "Minmi", level: 4, length: 3.0, period: "", diet: "", geo: "" },
  { name: "Epidexipteryx", wiki: "Epidexipteryx", level: 5, length: 0.25, period: "", diet: "", geo: "" },
  { name: "Ornitholestes", wiki: "Ornitholestes", level: 3, length: 2.0, period: "Jurassic", diet: "Carnivore", geo: "" },
  { name: "Nanuqsaurus", wiki: "Nanuqsaurus", level: 3, length: 7.0, period: "Late Cretaceous", diet: "Carnivore", geo: "" },
  { name: "Giraffatitan", wiki: "Giraffatitan", level: 3, length: 26.0, period: "Jurassic", diet: "Herbivore", geo: "North America, Africa, Tanzania" },
  { name: "Dicraeosaurus", wiki: "Dicraeosaurus", level: 5, length: 12.0, period: "Jurassic", diet: "Herbivore", geo: "Tanzania" },
  { name: "Nigersaurus", wiki: "Nigersaurus", level: 1, length: 9.0, period: "Cretaceous", diet: "Herbivore", geo: "Niger" },
  { name: "Caudipteryx", wiki: "Caudipteryx", level: 4, length: 1.0, period: "Early Cretaceous", diet: "", geo: "China" },
  { name: "Rajasaurus", wiki: "Rajasaurus", level: 3, length: 7.0, period: "Late Cretaceous", diet: "Carnivore", geo: "India" },
  { name: "Riojasaurus", wiki: "Riojasaurus", level: 5, length: 10.0, period: "Late Triassic", diet: "Herbivore", geo: "South America, Argentina" },
  { name: "Heterodontosaurus", wiki: "Heterodontosaurus", level: 4, length: 1.5, period: "Early Jurassic", diet: "", geo: "South Africa" },
  { name: "Austroraptor", wiki: "Austroraptor", level: 3, length: 5.0, period: "Late Cretaceous", diet: "Carnivore", geo: "Argentina" },
  { name: "Hypacrosaurus", wiki: "Hypacrosaurus", level: 4, length: 9.0, period: "Late Cretaceous", diet: "", geo: "North America, Canada, United States" },
  { name: "Sinovenator", wiki: "Sinovenator", level: 5, length: 1.0, period: "Cretaceous", diet: "", geo: "China" },
  { name: "Alamosaurus", wiki: "Alamosaurus", level: 3, length: 30.0, period: "Late Cretaceous", diet: "Herbivore", geo: "North America, South America" },
  { name: "Elaphrosaurus", wiki: "Elaphrosaurus", level: 4, length: 6.2, period: "Late Jurassic", diet: "Omnivore", geo: "Africa, Tanzania" },
  { name: "Wuerhosaurus", wiki: "Wuerhosaurus", level: 4, length: 7.0, period: "Early Cretaceous", diet: "Herbivore", geo: "China" },
  { name: "Jobaria", wiki: "Jobaria", level: 5, length: 18.0, period: "Jurassic", diet: "Herbivore", geo: "Niger" },
  { name: "Patagosaurus", wiki: "Patagosaurus", level: 5, length: 15.0, period: "", diet: "Herbivore", geo: "Argentina" },
  { name: "Unenlagia", wiki: "Unenlagia", level: 5, length: 2.5, period: "Late Cretaceous", diet: "Carnivore", geo: "South America" },
  { name: "Torosaurus", wiki: "Torosaurus", level: 3, length: 7.5, period: "Late Cretaceous", diet: "Herbivore", geo: "North America" },
  { name: "Megalosaurus", wiki: "Megalosaurus", level: 2, length: 9.0, period: "Middle Jurassic", diet: "Carnivore", geo: "England" },
  { name: "Prosaurolophus", wiki: "Prosaurolophus", level: 5, length: 8.0, period: "Late Cretaceous", diet: "Herbivore", geo: "North America" },
  { name: "Ornithomimus", wiki: "Ornithomimus", level: 3, length: 3.8, period: "Late Cretaceous", diet: "Omnivore", geo: "North America" },
  { name: "Dromaeosaurus", wiki: "Dromaeosaurus", level: 3, length: 1.8, period: "Late Cretaceous", diet: "Carnivore", geo: "United States" },
  { name: "Stegoceras", wiki: "Stegoceras", level: 4, length: 2.5, period: "Late Cretaceous", diet: "", geo: "North America, Canada" },
  { name: "Melanorosaurus", wiki: "Melanorosaurus", level: 5, length: 8.0, period: "Late Triassic", diet: "Omnivore", geo: "South Africa" },
  { name: "Masiakasaurus", wiki: "Masiakasaurus", level: 4, length: 2.1, period: "Late Cretaceous", diet: "Carnivore", geo: "South America" },
  { name: "Medusaceratops", wiki: "Medusaceratops", level: 5, length: 6.0, period: "Late Cretaceous", diet: "Herbivore", geo: "United States" },
  { name: "Prenocephale", wiki: "Prenocephale", level: 5, length: 2.0, period: "Late Cretaceous", diet: "", geo: "Mongolia" },
  { name: "Monolophosaurus", wiki: "Monolophosaurus", level: 3, length: 5.5, period: "Middle Jurassic", diet: "Carnivore", geo: "China" },
  { name: "Hypsilophodon", wiki: "Hypsilophodon", level: 3, length: 2.0, period: "Early Cretaceous", diet: "Herbivore", geo: "England" },
  { name: "Zhenyuanlong", wiki: "Zhenyuanlong", level: 5, length: 1.2, period: "Cretaceous", diet: "Carnivore", geo: "China" },
  { name: "Centrosaurus", wiki: "Centrosaurus", level: 3, length: 6.0, period: "Late Cretaceous", diet: "", geo: "Canada" },
  { name: "Beipiaosaurus", wiki: "Beipiaosaurus", level: 4, length: 2.2, period: "Early Cretaceous", diet: "Carnivore", geo: "China" },
  { name: "Torvosaurus", wiki: "Torvosaurus", level: 3, length: 10.7, period: "Late Jurassic", diet: "Carnivore", geo: "Tanzania, Portugal, England" },
  { name: "Alioramus", wiki: "Alioramus", level: 3, length: 6.0, period: "Late Cretaceous", diet: "Carnivore", geo: "Asia, Mongolia" },
  { name: "Tenontosaurus", wiki: "Tenontosaurus", level: 3, length: 7.0, period: "Early Cretaceous", diet: "Herbivore", geo: "North America" },
  { name: "Rapetosaurus", wiki: "Rapetosaurus", level: 4, length: 15.0, period: "Cretaceous", diet: "Herbivore", geo: "" },
  { name: "Pinacosaurus", wiki: "Pinacosaurus", level: 4, length: 5.0, period: "Late Cretaceous", diet: "Herbivore", geo: "Asia, China, Mongolia" },
  { name: "Compsognathus", wiki: "Compsognathus", level: 2, length: 1.0, period: "Jurassic", diet: "Carnivore", geo: "Europe, France, Germany" },
  { name: "Dreadnoughtus", wiki: "Dreadnoughtus", level: 3, length: 26.0, period: "Cretaceous", diet: "Herbivore", geo: "Argentina" },
  { name: "Acrocanthosaurus", wiki: "Acrocanthosaurus", level: 2, length: 11.5, period: "Early Cretaceous", diet: "", geo: "North America" },
  { name: "Yangchuanosaurus", wiki: "Yangchuanosaurus", level: 3, length: 11.0, period: "Middle Jurassic", diet: "Herbivore", geo: "North America, Europe, China" },
  { name: "Stygimoloch", wiki: "Stygimoloch", level: 4, length: 3.0, period: "Late Cretaceous", diet: "", geo: "North America" },
  { name: "Homalocephale", wiki: "Homalocephale", level: 5, length: 1.8, period: "Late Cretaceous", diet: "Omnivore", geo: "Mongolia" },
  { name: "Puertasaurus", wiki: "Puertasaurus", level: 4, length: 30.0, period: "Late Cretaceous", diet: "Herbivore", geo: "South America, Argentina" },
  { name: "Avimimus", wiki: "Avimimus", level: 5, length: 1.5, period: "Cretaceous", diet: "Carnivore", geo: "Mongolia" },
  { name: "Polacanthus", wiki: "Polacanthus", level: 4, length: 4.0, period: "Cretaceous", diet: "Herbivore", geo: "England" },
  { name: "Nodosaurus", wiki: "Nodosaurus", level: 3, length: 6.0, period: "Late Cretaceous", diet: "Herbivore", geo: "" },
  { name: "Nasutoceratops", wiki: "Nasutoceratops", level: 3, length: 4.5, period: "Late Cretaceous", diet: "", geo: "North America" },
  { name: "Saltasaurus", wiki: "Saltasaurus", level: 4, length: 12.0, period: "Late Cretaceous", diet: "Herbivore", geo: "Argentina" },
  { name: "Majungasaurus", wiki: "Majungasaurus", level: 2, length: 8.0, period: "Cretaceous", diet: "Carnivore", geo: "" },
  { name: "Barosaurus", wiki: "Barosaurus", level: 3, length: 26, period: "Late Jurassic (156–145 Ma)", diet: "Herbivore", geo: "North America" },
  { name: "Bambiraptor", wiki: "Bambiraptor", level: 4, length: 1.0, period: "Late Cretaceous", diet: "Carnivore", geo: "" },
  { name: "Dromiceiomimus", wiki: "Dromiceiomimus", level: 5, length: 3.5, period: "Late Cretaceous", diet: "Carnivore", geo: "Canada" },
  { name: "Tarchia", wiki: "Tarchia", level: 4, length: 5.5, period: "Cretaceous", diet: "Herbivore", geo: "Mongolia" },
  { name: "Guanlong", wiki: "Guanlong", level: 3, length: 3.0, period: "Late Jurassic", diet: "", geo: "China" },
];
