// Dino data: name, wiki article title, difficulty level (1-5), length in metres.
// Facts are fetched live from the Wikipedia summary API — nothing hardcoded here.
const DINOS = [
  // ── Level 1 – Super Famous ────────────────────────────────────────────────
  { name: "Tyrannosaurus Rex",    wiki: "Tyrannosaurus",        level: 1, length: 12   },
  { name: "Triceratops",          wiki: "Triceratops",          level: 1, length: 9    },
  { name: "Stegosaurus",          wiki: "Stegosaurus",          level: 1, length: 9    },
  { name: "Brachiosaurus",        wiki: "Brachiosaurus",        level: 1, length: 26   },
  { name: "Velociraptor",         wiki: "Velociraptor",         level: 1, length: 2    },
  { name: "Ankylosaurus",         wiki: "Ankylosaurus",         level: 1, length: 10   },
  { name: "Diplodocus",           wiki: "Diplodocus",           level: 1, length: 27   },
  { name: "Spinosaurus",          wiki: "Spinosaurus",          level: 1, length: 15   },
  { name: "Pteranodon",           wiki: "Pteranodon",           level: 1, length: 1.8  },
  { name: "Apatosaurus",          wiki: "Apatosaurus",          level: 1, length: 23   },
  { name: "Allosaurus",           wiki: "Allosaurus",           level: 1, length: 12   },
  { name: "Iguanodon",            wiki: "Iguanodon",            level: 1, length: 10   },

  // ── Level 2 – Well Known ──────────────────────────────────────────────────
  { name: "Parasaurolophus",      wiki: "Parasaurolophus",      level: 2, length: 10   },
  { name: "Pachycephalosaurus",   wiki: "Pachycephalosaurus",   level: 2, length: 5    },
  { name: "Carnotaurus",          wiki: "Carnotaurus",          level: 2, length: 9    },
  { name: "Dilophosaurus",        wiki: "Dilophosaurus",        level: 2, length: 6    },
  { name: "Gallimimus",           wiki: "Gallimimus",           level: 2, length: 6    },
  { name: "Mosasaurus",           wiki: "Mosasaurus",           level: 2, length: 17   },
  { name: "Archaeopteryx",        wiki: "Archaeopteryx",        level: 2, length: 0.5  },
  { name: "Edmontosaurus",        wiki: "Edmontosaurus",        level: 2, length: 13   },
  { name: "Deinonychus",          wiki: "Deinonychus",          level: 2, length: 3.4  },
  { name: "Coelophysis",          wiki: "Coelophysis",          level: 2, length: 3    },
  { name: "Troodon",              wiki: "Troodon",              level: 2, length: 2.4  },
  { name: "Utahraptor",           wiki: "Utahraptor",           level: 2, length: 6    },
  { name: "Corythosaurus",        wiki: "Corythosaurus",        level: 2, length: 9    },
  { name: "Plateosaurus",         wiki: "Plateosaurus",         level: 2, length: 8    },

  // ── Level 3 – Intermediate ────────────────────────────────────────────────
  { name: "Baryonyx",             wiki: "Baryonyx",             level: 3, length: 10   },
  { name: "Ceratosaurus",         wiki: "Ceratosaurus",         level: 3, length: 6    },
  { name: "Maiasaura",            wiki: "Maiasaura",            level: 3, length: 9    },
  { name: "Oviraptor",            wiki: "Oviraptor",            level: 3, length: 2    },
  { name: "Carcharodontosaurus",  wiki: "Carcharodontosaurus",  level: 3, length: 13   },
  { name: "Suchomimus",           wiki: "Suchomimus",           level: 3, length: 11   },
  { name: "Kentrosaurus",         wiki: "Kentrosaurus",         level: 3, length: 4.5  },
  { name: "Protoceratops",        wiki: "Protoceratops",        level: 3, length: 1.8  },
  { name: "Camarasaurus",         wiki: "Camarasaurus",         level: 3, length: 18   },
  { name: "Camptosaurus",         wiki: "Camptosaurus",         level: 3, length: 7    },
  { name: "Ouranosaurus",         wiki: "Ouranosaurus",         level: 3, length: 8    },
  { name: "Psittacosaurus",       wiki: "Psittacosaurus",       level: 3, length: 2    },
  { name: "Saurolophus",          wiki: "Saurolophus",          level: 3, length: 9    },
  { name: "Megaraptor",           wiki: "Megaraptor",           level: 3, length: 8    },
  { name: "Concavenator",         wiki: "Concavenator",         level: 3, length: 6    },

  // ── Level 4 – Advanced ────────────────────────────────────────────────────
  { name: "Styracosaurus",        wiki: "Styracosaurus",        level: 4, length: 5.5  },
  { name: "Therizinosaurus",      wiki: "Therizinosaurus",      level: 4, length: 10   },
  { name: "Gorgosaurus",          wiki: "Gorgosaurus",          level: 4, length: 9    },
  { name: "Amargasaurus",         wiki: "Amargasaurus",         level: 4, length: 10   },
  { name: "Euoplocephalus",       wiki: "Euoplocephalus",       level: 4, length: 6    },
  { name: "Pachyrhinosaurus",     wiki: "Pachyrhinosaurus",     level: 4, length: 8    },
  { name: "Lambeosaurus",         wiki: "Lambeosaurus",         level: 4, length: 9    },
  { name: "Albertosaurus",        wiki: "Albertosaurus",        level: 4, length: 9    },
  { name: "Pentaceratops",        wiki: "Pentaceratops",        level: 4, length: 8    },
  { name: "Anchiceratops",        wiki: "Anchiceratops",        level: 4, length: 6    },
  { name: "Irritator",            wiki: "Irritator_(dinosaur)", level: 4, length: 8    },
  { name: "Scelidosaurus",        wiki: "Scelidosaurus",        level: 4, length: 4    },
  { name: "Tsintaosaurus",        wiki: "Tsintaosaurus",        level: 4, length: 8    },

  // ── Level 5 – Expert ──────────────────────────────────────────────────────
  { name: "Argentinosaurus",      wiki: "Argentinosaurus",      level: 5, length: 35   },
  { name: "Quetzalcoatlus",       wiki: "Quetzalcoatlus",       level: 5, length: 3    },
  { name: "Microraptor",          wiki: "Microraptor",          level: 5, length: 0.8  },
  { name: "Giganotosaurus",       wiki: "Giganotosaurus",       level: 5, length: 13   },
  { name: "Eoraptor",             wiki: "Eoraptor",             level: 5, length: 1    },
  { name: "Sauroposeidon",        wiki: "Sauroposeidon",        level: 5, length: 34   },
  { name: "Sinosauropteryx",      wiki: "Sinosauropteryx",      level: 5, length: 1    },
  { name: "Herrerasaurus",        wiki: "Herrerasaurus",        level: 5, length: 4.5  },
  { name: "Dracorex",             wiki: "Dracorex",             level: 5, length: 3    },
  { name: "Nothronychus",         wiki: "Nothronychus",         level: 5, length: 4.5  },
  { name: "Magyarosaurus",        wiki: "Magyarosaurus",        level: 5, length: 6    },
  { name: "Abrictosaurus",        wiki: "Abrictosaurus",        level: 5, length: 1.2  },
  { name: "Yinlong",              wiki: "Yinlong",              level: 5, length: 1.2  },
  { name: "Limusaurus",           wiki: "Limusaurus",           level: 5, length: 1.7  },
];
