// Auto-generated by scripts/fetch-dino-data.py — do not edit manually.
// Run `make fetch-data` to refresh.
const DINO_DATA = {
  "Tyrannosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Tyrannosaurus_Rex_Holotype.jpg/960px-Tyrannosaurus_Rex_Holotype.jpg",
    "short": "Tyrannosaurus is a genus of large theropod dinosaur.",
    "full": "The type species Tyrannosaurus rex, often shortened to T. rex or colloquially t-rex, is one of the best represented theropods. It lived throughout what is now western North America, on what was then an island continent known as Laramidia. Tyrannosaurus had a much wider range than other tyrannosaurids. Fossils are found in a variety of geological formations dating to the late Maastrichtian age of the late Cretaceous period, 69 to 66 million years ago, with isolated specimens possibly indicating an earlier origin in the middle Campanian age. It was one of the last known members of the tyrannosaurids and among the last non-avian dinosaurs to exist before the Cretaceous–Paleogene extinction event."
  },
  "Triceratops": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/LA-Triceratops_mount-2.jpg/960px-LA-Triceratops_mount-2.jpg",
    "short": "Triceratops is a genus of chasmosaurine ceratopsian dinosaur that lived during the late Maastrichtian age of the Late Cretaceous period, about 68 to 66 million years ago on the island continent of Laramidia, now forming western North America.",
    "full": "It was one of the last-known non-avian dinosaurs and lived until the Cretaceous–Paleogene extinction event 66 million years ago. The name Triceratops, which means 'three-horned face', is derived from the Ancient Greek words τρί-, meaning \"three\", κέρας, meaning \"horn\", and ὤψ, meaning \"face\"."
  },
  "Stegosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Journal.pone.0138352.g001A.jpg/960px-Journal.pone.0138352.g001A.jpg",
    "short": "Stegosaurus is a genus of herbivorous four-legged armored dinosaurs from the Late Jurassic, characterized by the distinctive kite-shaped upright plates along their backs and spikes on their tails.",
    "full": "Fossils of the genus have been found in the western United States and in Portugal, where they are found in Kimmeridgian- to Tithonian-aged strata, dating to between 155 and 145 million years ago. Of the species that have been classified in the upper Morrison Formation of the western US, only three are universally recognized: S. stenops, S. ungulatus and S. sulcatus. The remains of over 80 individual animals of this genus have been found. Stegosaurus would have lived alongside dinosaurs such as Apatosaurus, Diplodocus, Camarasaurus and Allosaurus, the latter of which may have preyed on it."
  },
  "Brachiosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Brachiosaurus_mount.jpg/960px-Brachiosaurus_mount.jpg",
    "short": "Brachiosaurus is a genus of sauropod dinosaur that lived in North America during the Late Jurassic, about 155.6 to 145.5 million years ago.",
    "full": "It was first described by American paleontologist Elmer S. Riggs in 1903 from fossils found in the Colorado River valley in western Colorado, United States. Riggs named the dinosaur Brachiosaurus altithorax; the generic name is Greek for \"arm lizard\", in reference to its proportionately long arms, and the specific name means \"deep chest\". Brachiosaurus is estimated to have been between 18 and 22 meters long; body mass estimates of the subadult holotype specimen range from 28.3 to 46.9 metric tons. It had a disproportionately long neck, small skull, and large overall size, all of which are typical for sauropods. Atypically, Brachiosaurus had longer forelimbs than hindlimbs, which resulted in a steeply inclined trunk, and a proportionally shorter tail."
  },
  "Velociraptor": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Velociraptor_skeleton_white_background.jpg/960px-Velociraptor_skeleton_white_background.jpg",
    "short": "Velociraptor is a genus of small dromaeosaurid dinosaurs that lived in Asia during the Late Cretaceous epoch, about 75 million to 71 million years ago (Mya).",
    "full": "Two species are currently recognized, although others have been assigned in the past. The type species is V. mongoliensis, named and described in 1924. Fossils of this species have been discovered in the Djadochta Formation, Mongolia. A second species, V. osmolskae, was named in 2008 for skull material from the Bayan Mandahu Formation, China. A possible record is known from the Nemegt Formation."
  },
  "Ankylosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Ankylosaur_head_-_cast_-_Custer_County_Montana_-_Museum_of_the_Rockies_-_2013-07-08.jpg/960px-Ankylosaur_head_-_cast_-_Custer_County_Montana_-_Museum_of_the_Rockies_-_2013-07-08.jpg",
    "short": "Ankylosaurus is a genus of armored dinosaur.",
    "full": "Its fossils have been found in geological formations dating to the very end of the Cretaceous Period, about 70-66 million years ago, in western North America, making it among the last of the non-avian dinosaurs. It was named by Barnum Brown in 1908; it is monotypic, containing only A. magniventris. The generic name means \"fused\" or \"bent lizard\", and the specific name means \"great belly\". A handful of specimens have been excavated to date, but a complete skeleton has not been discovered. Though other members of Ankylosauria are represented by more extensive fossil material, Ankylosaurus is often considered the archetypal member of its group, despite having some unusual features."
  },
  "Diplodocus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/CM_Diplodocus.jpg/960px-CM_Diplodocus.jpg",
    "short": "Diplodocus is an extinct genus of diplodocid sauropod dinosaurs known from the Late Jurassic of North America.",
    "full": "The first fossils of Diplodocus were discovered in 1877 by S. W. Williston. The generic name, coined by Othniel Charles Marsh in 1878, is a Neo-Latin term derived from Greek διπλός (diplos) \"double\" and δοκός (dokos) \"beam\", in reference to the double-beamed chevron bones located in the underside of the tail, which were then considered unique."
  },
  "Spinosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/FSAC-KK-11888.jpg/960px-FSAC-KK-11888.jpg",
    "short": "Spinosaurus is a genus of large spinosaurid theropod dinosaurs that lived in what is now North Africa during the Cenomanian stage of the Late Cretaceous period, about 100 to 94 million years ago.",
    "full": "The genus was known first from Egyptian remains discovered in 1912 and described by German palaeontologist Ernst Stromer in 1915. The original remains were destroyed in World War II, but additional material came to light in the early 21st century. It is unclear whether one or two species are represented in the fossils reported in the scientific literature. The type species, S. aegyptiacus, is mainly known from the Bahariya Formation in Egypt and the Kem Kem beds in Morocco. The other species, S. mirabilis, is known from the Farak Formation in Niger. Although another potential species, S. maroccanus, has been recovered from the Kem Kem beds, this dubious species is likely a junior synonym of S. aegyptiacus. Other possible junior synonyms include Sigilmassasaurus from the Kem Kem beds and Oxalaia from the Alcântara Formation in Brazil, though other researchers propose both genera to be distinct taxa."
  },
  "Pteranodon": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Pteranodon_amnh_martyniuk.jpg/960px-Pteranodon_amnh_martyniuk.jpg",
    "short": "Pteranodon (; from Ancient Greek pteron 'wing', an- 'without', and odon 'tooth' is a genus of pterosaur that included some of the largest known flying reptiles, with P. longiceps having a wingspan of over 6 m.",
    "full": "They lived during the late Cretaceous geological period of North America in present-day Kansas, Nebraska, Wyoming, South Dakota and Alabama. More fossil specimens of Pteranodon have been found than any other pterosaur, with about 1,200 specimens known to science, many of them well preserved with nearly complete skulls and articulated skeletons. It was an important part of the animal community in the Western Interior Seaway."
  },
  "Apatosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Apatosaurus_louisae_-_CM.jpg/960px-Apatosaurus_louisae_-_CM.jpg",
    "short": "Apatosaurus is a genus of herbivorous sauropod dinosaur that lived in North America during the Late Jurassic period.",
    "full": "Othniel Charles Marsh described and named the first-known species, Apatosaurus ajax, in 1877, and a second species, Apatosaurus louisae, was discovered and named by William H. Holland in 1916. Apatosaurus lived about 152 to 151 million years ago (mya), during the late Kimmeridgian to early Tithonian age, and are now known from fossils in the Morrison Formation of modern-day Colorado, Oklahoma, New Mexico, Wyoming, and Utah in the United States. Apatosaurus had an average length of 21–23 m (69–75 ft), and an average mass of 16.4–22.4 t. A few specimens indicate a maximum length of 11–30% greater than average and a mass of approximately 33 t."
  },
  "Allosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/WLA_hmns_Allosaurus_White_Background.jpg/960px-WLA_hmns_Allosaurus_White_Background.jpg",
    "short": "Allosaurus is a genus of theropod dinosaur that lived 155 to 145 million years ago during the Late Jurassic period.",
    "full": "The first fossil remains that could definitively be ascribed to this genus were described in 1877 by Othniel C. Marsh. The name \"Allosaurus\" means \"different lizard\", alluding to its lightweight vertebrae, which Marsh believed were unique. The genus has a very complicated taxonomy and includes at least three valid species, the best known of which is A. fragilis. The bulk of Allosaurus remains come from North America's Morrison Formation, with material also known from the Alcobaça, Bombarral, and Lourinhã formations in Portugal. It was known for over half of the 20th century as Antrodemus, but a study of the abundant remains from the Cleveland-Lloyd Dinosaur Quarry returned the name \"Allosaurus\" to prominence. As one of the first well-known theropod dinosaurs, it has long attracted attention outside of paleontological circles."
  },
  "Iguanodon": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Iguanodon_de_Bernissart_IRSNB_01.JPG/960px-Iguanodon_de_Bernissart_IRSNB_01.JPG",
    "short": "Iguanodon, named in 1825, is a genus of iguanodontian dinosaur.",
    "full": "While many species found worldwide have been classified in the genus Iguanodon, dating from the Late Jurassic to Early Cretaceous, taxonomic revision in the early 21st century has defined Iguanodon to be based on at least one well-substantiated species: Iguanodon bernissartensis, which lived during the Barremian to early Aptian ages of the Early Cretaceous in Belgium, Germany, England, and Spain, between about 126 and 122 million years ago. Iguanodon was a large, bulky herbivore, measuring up to 9–11 metres (30–36 ft) in length and 4.5 metric tons in body mass. Distinctive features include large thumb spikes, which were possibly used for defense against predators, combined with long prehensile fifth fingers able to forage for food."
  },
  "Parasaurolophus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/FMNH_Parasaurolophus_fossil.jpg/960px-FMNH_Parasaurolophus_fossil.jpg",
    "short": "Parasaurolophus is a genus of hadrosaurid \"duck-billed\" dinosaur that lived in what is now western North America and possibly Asia during the Late Cretaceous period, about 76.5–73 million years ago.",
    "full": "It was a large herbivore that could reach over 9 metres (30 ft) long and weigh over 5 metric tons, and were able to move as a biped and a quadruped. Three species are universally recognized: P. walkeri, P. tubicen, and the short-crested P. cyrtocristatus. Additionally, a fourth species, P. jiayinensis, has been proposed, although it is more commonly placed in the separate genus Charonosaurus. Remains are known from Alberta, New Mexico, and Utah, as well as possibly Heilongjiang if Charonosaurus is in fact part of the genus. The genus was first described in 1922 by William Parks from a skull and partial skeleton found in Alberta."
  },
  "Pachycephalosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Pachycephalosaurus_wyomingensis_ROM.jpg/960px-Pachycephalosaurus_wyomingensis_ROM.jpg",
    "short": "Pachycephalosaurus is a genus of pachycephalosaurid ornithischian dinosaur.",
    "full": "The type species, P. wyomingensis, is the only known definitive species. The possibly synonymous taxon, Stygimoloch, might represent a distinct genus or a second species, P. spinifer. It lived during the Maastrichtian age of the Late Cretaceous period in what is now western North America. Remains have been excavated in Montana, South Dakota, Wyoming, and Alberta. Mainly known from a single skull and a few extremely thick skull roofs, Pachycephalosaurus is estimated to have reached 4.5 m (15 ft) long and weighed 370–450 kg (820–990 lb). More complete fossils would come to be found in the following years."
  },
  "Carnotaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Carnotaurus%2C_Chlup%C3%A1%C4%8D_Museum%2C_Prague-2.jpg/960px-Carnotaurus%2C_Chlup%C3%A1%C4%8D_Museum%2C_Prague-2.jpg",
    "short": "Carnotaurus is a genus of theropod dinosaur that lived in South America during the Late Cretaceous period, between 69 and 66 million years ago.",
    "full": "The only species is Carnotaurus sastrei. Known from a single well-preserved skeleton, it is one of the best-understood theropods from the Southern Hemisphere. The skeleton, found in 1984, was uncovered in the Chubut Province of Argentina from rocks of the La Colonia Formation. Carnotaurus is a derived member of the Abelisauridae, a group of large theropods that occupied the large predatorial niche in the southern landmasses of Gondwana during the late Cretaceous. Within the Abelisauridae, the genus is often considered a member of the Brachyrostra, a clade of short-snouted forms restricted to South America."
  },
  "Dilophosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/DilophosaurusROM1.JPG/960px-DilophosaurusROM1.JPG",
    "short": "Dilophosaurus is a genus of theropod dinosaurs that lived in what is now North America during the Early Jurassic, about 186 million years ago.",
    "full": "Three skeletons were discovered in northern Arizona in 1940, and the two best preserved were collected in 1942. The most complete specimen became the holotype of a new species in the genus Megalosaurus, named M. wetherilli by Samuel P. Welles in 1954. Welles found a larger skeleton belonging to the same species in 1964. Realizing it bore crests on its skull, he assigned the species to the new genus Dilophosaurus in 1970, as Dilophosaurus wetherilli. The genus name means \"two-crested lizard\", and the species name honors John Wetherill, an explorer and amateur archeologist. Further specimens have since been found, including an infant. Fossil footprints have also been attributed to the animal, including resting traces. Another species, Dilophosaurus sinensis from China, was named in 1993, but was later found to belong to the genus Sinosaurus."
  },
  "Gallimimus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Gallimimus_bullatus.001_-_Natural_History_Museum_of_London.JPG/960px-Gallimimus_bullatus.001_-_Natural_History_Museum_of_London.JPG",
    "short": "Gallimimus is a genus of theropod dinosaur that lived in what is now Mongolia during the Late Cretaceous period.",
    "full": "Several fossils in various stages of growth were discovered by Polish-Mongolian expeditions in the Gobi Desert of Mongolia during the 1960s; a large skeleton discovered in this region was made the holotype specimen of the new genus and species Gallimimus bullatus in 1972. The generic name means \"chicken mimic\", referring to the similarities between its neck vertebrae and those of the Galliformes. The specific name is derived from bulla, a golden capsule worn by Roman youth, in reference to a bulbous structure at the base of the skull of Gallimimus. At the time it was named, the fossils of Gallimimus represented the most complete and best preserved ornithomimid material yet discovered, and the genus remains one of the best known members of the group."
  },
  "Mosasaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Mosasaurus_hoffmannii_-_skeleton.jpg/960px-Mosasaurus_hoffmannii_-_skeleton.jpg",
    "short": "Mosasaurus is the type genus of the Mosasauridae, an extinct group of aquatic squamate reptiles.",
    "full": "It lived from about 82 to 66 million years ago during the Campanian and Maastrichtian stages of the Late Cretaceous. The genus was one of the first Mesozoic marine reptiles known to science—the first fossils of Mosasaurus were found as skulls in a chalk quarry near the Dutch city of Maastricht in the late 18th century, and were initially thought to be crocodiles or whales. One skull discovered around 1780 was famously nicknamed the \"great animal of Maastricht\". In 1808, naturalist Georges Cuvier concluded that it belonged to a giant marine lizard with similarities to monitor lizards but otherwise unlike any known living animal. This concept was revolutionary at the time and helped support the then-developing ideas of extinction. Cuvier did not designate a scientific name for the animal; this was done by William Daniel Conybeare in 1822 when he named it Mosasaurus in reference to its origin in fossil deposits near the Meuse River. The exact affinities of Mosasaurus as a squamate remain controversial, and scientists continue to debate whether its closest living relatives are monitor lizards or snakes."
  },
  "Archaeopteryx": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Archaeopteryx_lithographica_%28Berlin_specimen%29.jpg/960px-Archaeopteryx_lithographica_%28Berlin_specimen%29.jpg",
    "short": "Archaeopteryx, sometimes referred to by its German name, \"Urvogel \" is a genus of bird-like dinosaurs.",
    "full": "The genus name derives from the Ancient Greek ἀρχαῖος, meaning 'ancient', and πτέρυξ, meaning 'feather, wing'. Between the late 19th century and the early 21st century, Archaeopteryx was generally accepted by palaeontologists and popular reference books as the oldest known bird. Older potential avialans have since been identified, including Anchiornis, Xiaotingia, Aurornis, and Baminornis."
  },
  "Edmontosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Edmontosaurus_Family_Clean.png/960px-Edmontosaurus_Family_Clean.png",
    "short": "Edmontosaurus, often colloquially and historically known as Anatosaurus or Anatotitan, is a genus of hadrosaurid (duck-billed) dinosaur.",
    "full": "It contains two known species: Edmontosaurus regalis and Edmontosaurus annectens. Fossils of E. regalis have been found in rocks of western North America that date from the late Campanian age of the Cretaceous period 73 million years ago, while those of E. annectens were found in the same geographic region from rocks dated to the end of the Maastrichtian age, 66 million years ago. Edmontosaurus was one of the last non-avian dinosaurs ever to exist, and lived alongside dinosaurs like Triceratops, Tyrannosaurus, Ankylosaurus, and Pachycephalosaurus shortly before the Cretaceous–Paleogene extinction event."
  },
  "Deinonychus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Deinonychus_FMNH.jpg/960px-Deinonychus_FMNH.jpg",
    "short": "Deinonychus is a genus of dromaeosaurid theropod dinosaur with one described species, Deinonychus antirrhopus.",
    "full": "This species, which could grow up to 3.4 meters (11 ft) long, lived during the Early and Late Cretaceous Period, about 115–93.9 million years ago. Fossils have been recovered from the U.S. states of Montana, Utah, Wyoming, and Oklahoma, in rocks of the Cloverly Formation and Antlers Formation, though teeth that may belong to Deinonychus have been found much farther east in Maryland."
  },
  "Coelophysis": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Coelophysis_bauri_mount.jpg/960px-Coelophysis_bauri_mount.jpg",
    "short": "Coelophysis is an extinct genus of coelophysid theropod dinosaurs that lived approximately 215 to 201.4 million years ago during the late Triassic period from the middle Norian to Rhaetian age in what is now the southwestern United States.",
    "full": "Megapnosaurus was once considered to be a species within this genus, but this interpretation has been challenged and the genus Megapnosaurus is now considered valid."
  },
  "Troodon": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Troodon_MOR_full.png/960px-Troodon_MOR_full.png",
    "short": "Troodon is a controversial genus of relatively small, bird-like theropod dinosaurs definitively known from the Campanian age of the Late Cretaceous period.",
    "full": "It includes at least one species, Troodon formosus, known from Montana. Discovered in October 1855, T. formosus was among the first dinosaurs found in North America, although it was thought to be a lizard until 1877."
  },
  "Utahraptor": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/BYU_Utahraptor_skeletal_mount.jpg/960px-BYU_Utahraptor_skeletal_mount.jpg",
    "short": "Utahraptor is a genus of large dromaeosaurid dinosaur that lived during the Early Cretaceous period from around 139 to 135 million years ago in what is now the United States.",
    "full": "The genus was described in 1993 by American paleontologist James Kirkland and colleagues with the type species Utahraptor ostrommaysi, based on fossils that had been unearthed earlier from the Cedar Mountain Formation of Utah. Later, many additional specimens were described including those from the skull and postcranium in addition to those of younger individuals."
  },
  "Corythosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Carnegie_Corythosaurus.jpg/960px-Carnegie_Corythosaurus.jpg",
    "short": "Corythosaurus is a genus of hadrosaurid \"duck-billed\" dinosaur from the Late Cretaceous period, about 77–75.7 million years ago, in what is now western North America.",
    "full": "Its name is derived from the Greek word κόρυς, meaning \"helmet\", named and described in 1914 by Barnum Brown. Corythosaurus is now thought to be a lambeosaurine, thus related to Lambeosaurus, Nipponosaurus, Velafrons, Hypacrosaurus, and Olorotitan. Corythosaurus has an estimated length of 7.7–9 metres (25–30 ft) and has a skull, including the crest, that is 70.8 centimetres tall."
  },
  "Plateosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Plateosaurus_Skelett_2.jpg/960px-Plateosaurus_Skelett_2.jpg",
    "short": "Plateosaurus is a genus of plateosaurid dinosaur that lived during the Late Triassic epoch of the Triassic period, around 214 to 204 million years ago, in what is now Central and Northern Europe.",
    "full": "Plateosaurus is a basal (early) sauropodomorph dinosaur, a so-called \"prosauropod\". The type species is Plateosaurus trossingensis; before 2019, that honor was given to Plateosaurus engelhardti, but it was ruled as undiagnostic by the ICZN. Currently, there are three valid species; in addition to P. trossingensis, P. longiceps and P. gracilis are also known. However, others have been assigned in the past, and there is no broad consensus on the species taxonomy of plateosaurid dinosaurs. Similarly, there are a plethora of synonyms at the genus level."
  },
  "Baryonyx": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Baryonyx_walkeri_mount_NMNS.jpg/960px-Baryonyx_walkeri_mount_NMNS.jpg",
    "short": "Baryonyx is a genus of theropod dinosaur which lived in the Barremian stage of the Early Cretaceous period, about 130–125 million years ago.",
    "full": "The first skeleton was discovered in 1983 in the Smokejack Clay Pit, of Surrey, England, in sediments of the Weald Clay Formation, and became the holotype specimen of Baryonyx walkeri, named by palaeontologists Alan J. Charig and Angela C. Milner in 1986. The genus name Baryonyx comes from Ancient Greek βαρύς (barús), meaning \"heavy\" or \"strong\", and ὄνυξ (ónux), meaning \"claw\", alluding to the animal's very large claw on the first finger; the specific name, walkeri, refers to its discoverer, amateur fossil collector William J. Walker. The holotype specimen is one of the most complete theropod skeletons from the UK, and its discovery attracted media attention. Specimens later discovered in other parts of the United Kingdom and Iberia have also been assigned to the genus, though many have since been moved to new genera."
  },
  "Ceratosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Ceratosaurus_mount_utah_museum_1.jpg/960px-Ceratosaurus_mount_utah_museum_1.jpg",
    "short": "Ceratosaurus is a genus of carnivorous theropod dinosaur that lived during the Late Jurassic period in North America and Europe.",
    "full": "The genus was first described in 1884 by American paleontologist Othniel Charles Marsh based on a nearly complete skeleton discovered in Garden Park, Colorado, in rocks belonging to the Morrison Formation. The type species is Ceratosaurus nasicornis."
  },
  "Maiasaura": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Maiasaura_skeleton.jpg/960px-Maiasaura_skeleton.jpg",
    "short": "Maiasaura is a large herbivorous saurolophine hadrosaurid (\"duck-billed\") dinosaur genus that lived in the area currently covered by the state of Montana and the Canadian province of Alberta, in the Upper Cretaceous, from 86.3 to 70.6 million years ago.",
    "full": "Maiasaura is the state fossil of Montana."
  },
  "Oviraptor": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Oviraptor_holotype.jpg/960px-Oviraptor_holotype.jpg",
    "short": "Oviraptor is a genus of oviraptorid dinosaur that lived in Asia during the Late Cretaceous period.",
    "full": "The first remains were collected from the Djadokhta Formation of Mongolia in 1923 during a paleontological expedition led by Roy Chapman Andrews, and in the following year the genus and type species Oviraptor philoceratops were named by Henry Fairfield Osborn. The genus name refers to the initial thought of egg-stealing habits, and the specific name was intended to reinforce this view indicating a preference over ceratopsian eggs. Despite the fact that numerous specimens have been referred to the genus, Oviraptor is only known from a single partial skeleton regarded as the holotype, as well as a nest of about fifteen eggs and several small fragments from a juvenile."
  },
  "Carcharodontosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ultimate_Dinosaurs_Carcharodontosaurus.jpg/960px-Ultimate_Dinosaurs_Carcharodontosaurus.jpg",
    "short": "Carcharodontosaurus is a genus of large theropod dinosaur that lived in Northwest Africa from about 100 to 94 million years ago during the Cenomanian stage of the Cretaceous.",
    "full": "The taxon was first described in 1925 by French paleontologists Charles Depéret and Justin Savornin as Megalosaurus saharicus, based on two fossil teeth discovered in Algeria, which are now lost. A partial skeleton was discovered in Egypt as early as 1914 by crews of German paleontologist Ernst Stromer, although he did not report the find until 1931. Based on this specimen, together with the teeth previously described by Depéret and Savornin, Stromer established the genus Carcharodontosaurus and its type species C. saharicus. Although the Egyptian skeleton was destroyed during World War II, it was subsequently redescribed as the holotype (name-bearing) specimen of a distinct carcharodontosaurid genus, Tameryraptor. In 1995, a large incomplete skull attributed to C. saharicus was discovered in the Kem Kem Beds of Morocco, which was officially proposed as the neotype in 2007. In the same year, fossils unearthed from the Farak Formation of Niger were described and named as another species, C. iguidensis, though this taxon might belong to a different genus."
  },
  "Suchomimus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/CCM_Suchomimus_2018.jpg/960px-CCM_Suchomimus_2018.jpg",
    "short": "Suchomimus is a genus of large theropod dinosaur that lived in what is now Niger during the Aptian to Albian stages of the Early Cretaceous period, 112 million years ago.",
    "full": "The only known species is S. tenerensis, originally described in 1998 by paleontologist Paul Sereno and colleagues from several fossils discovered one year earlier in the Elrhaz Formation. Although these fossils come from multiple specimens, they represent one of the most anatomically well-documented spinosaurids. The animal's generic name, which means \"crocodile mimic\", alludes to its elongated skull and piscivorous adaptations, while the specific name refers to the Ténéré Desert, where the fossils were discovered."
  },
  "Kentrosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Berlin_Naturkundemuseum_Dino_Eingangshalle.jpg/960px-Berlin_Naturkundemuseum_Dino_Eingangshalle.jpg",
    "short": "Kentrosaurus is a genus of stegosaurid dinosaur from the Late Jurassic in Lindi Region of Tanzania.",
    "full": "The type species is K. aethiopicus, named and described by German palaeontologist Edwin Hennig in 1915. Often thought to be a \"primitive\" member of the Stegosauria, several recent cladistic analyses find it as more derived than many other stegosaurs, and a close relative of Stegosaurus from the North American Morrison Formation within the Stegosauridae."
  },
  "Protoceratops": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/0/04/Protoceratops-skeleton.jpg",
    "short": "Protoceratops is a genus of small protoceratopsid dinosaurs that lived in Asia during the Late Cretaceous, around 75 to 71 million years ago.",
    "full": "The genus Protoceratops includes two species: P. andrewsi and the larger P. hellenikorhinus. The former was described in 1923 with fossils from the Mongolian Djadokhta Formation, and the latter in 2001 with fossils from the Chinese Bayan Mandahu Formation. Protoceratops was initially believed to be an ancestor of ankylosaurians and larger ceratopsians, such as Triceratops and relatives, until the discoveries of other protoceratopsids. Populations of P. andrewsi may have evolved into Bagaceratops rozhdestvenskyi through anagenesis."
  },
  "Camarasaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Camarasaurus_lentus_Carnegie.jpg/960px-Camarasaurus_lentus_Carnegie.jpg",
    "short": "Camarasaurus is a genus of sauropod dinosaur that lived during the Late Jurassic in what is now the United States.",
    "full": "Its fossils are primarily known from the Morrison Formation dating to the Kimmeridgian and Tithonian ages of the Jurassic, between 155 and 145 million years ago (mya). It was named by Edward Drinker Cope in 1877; it definitively contains three species, C. supremus, the type species, C. grandis, and C. lentus, while some researchers consider C. lewisi to be in its own genus, Cathetosaurus. The generic name means \"chambered lizard\", referring to the hollow chambers, known as pleurocoels, in its cervical vertebrae. Hundreds of specimens have been excavated to date, including some nearly complete skeletons. It is among the best understood dinosaurs, with detailed studies of its anatomy, paleobiology, paleoecology, and more."
  },
  "Camptosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Camptosaurus_dispar_skeleton.jpg/960px-Camptosaurus_dispar_skeleton.jpg",
    "short": "Camptosaurus is an extinct genus of plant-eating, beaked ornithischian dinosaurs of the Late Jurassic period of western North America and possibly also Europe.",
    "full": "The name means 'flexible lizard'."
  },
  "Ouranosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Ouranosaurus_MSNVE_3714.png/960px-Ouranosaurus_MSNVE_3714.png",
    "short": "Ouranosaurus is a genus of herbivorous basal hadrosauriform dinosaur that lived during the Aptian stage of the Early Cretaceous of modern-day Niger and Cameroon.",
    "full": "Ouranosaurus measured about 7–8.3 metres (23–27 ft) long and weighed 2.2 metric tons. Two rather complete fossils were found in the Elrhaz Formation, Gadoufaoua deposits, Agadez, Niger, in 1965 and 1970, with a third indeterminate specimen known from the Koum Formation of Cameroon. The animal was named in 1976 by French paleontologist Philippe Taquet, the type species being Ouranosaurus nigeriensis. The generic name is a combination of ourane, a word with multiple meanings, and sauros, the Greek word for lizard. The specific epithet nigeriensis alludes to Niger, its country of discovery. As such, Ouranosaurus nigeriensis could be interpreted as \"brave lizard originating from Niger\"."
  },
  "Psittacosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/8/85/The_Childrens_Museum_of_Indianapolis_-_Psittacosaurus_skeleton_cast.jpg",
    "short": "Psittacosaurus is a genus of extinct ceratopsian dinosaur from the Early Cretaceous of what is now Asia, existing between 125 and 105 million years ago.",
    "full": "It is notable for being the most species-rich non-avian dinosaur genus. Up to 13 species are known, from across China, Mongolia, Russia, and Thailand. The species of Psittacosaurus were obligate bipeds at adulthood, with a high skull and a robust beak. One individual was found preserved with long filaments on the tail, similar to those of Tianyulong. Psittacosaurus probably had complex behaviours, based on the proportions and relative size of the brain. It may have been active for short periods of time during the day and night, and had well-developed senses of smell and vision."
  },
  "Saurolophus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Saurolophus_mount.jpg/960px-Saurolophus_mount.jpg",
    "short": "Saurolophus is a genus of large hadrosaurid dinosaur that lived during the Late Cretaceous period of North America and Asia, in what is now the Horseshoe Canyon and Nemegt formations respectively.",
    "full": "It is one of the few dinosaur genera known from multiple continents. The type species, S. osborni, was described by Barnum Brown in 1912 from Canadian fossils. A second valid species, S. angustirostris, is represented by numerous specimens from Mongolia, and was described by Anatoly Konstantinovich Rozhdestvensky. Saurolophus is distinguished by a spike-like crest which projects up and back from the skull. It was a herbivorous dinosaur which could move either bipedally or quadrupedally."
  },
  "Megaraptor": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Megaraptor_mount.jpg/960px-Megaraptor_mount.jpg",
    "short": "Megaraptor is a genus of large theropod dinosaur, the type genus and namesake of the clade Megaraptora and family Megaraptoridae.",
    "full": "Its fossils have been discovered in the Patagonian Portezuelo Formation of Argentina, South America, dating to the Turonian and Coniacian ages of the Late Cretaceous, roughly 90–88 million years ago. One species of Megaraptor, M. namunhuaiquii, has thus been named, known from seven partial or fragmentary skeletons, with only two including skull elements."
  },
  "Concavenator": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Concavenator.jpg/960px-Concavenator.jpg",
    "short": "Concavenator is a genus of carcharodontosaurian dinosaur that lived in Spain during the Early Cretaceous epoch, about 125 million years ago.",
    "full": "The genus contains a single species, Concavenator corcovatus, named and described in 2010 from a nearly complete skeleton collected from the Las Hoyas fossil site of the La Huérguina Formation."
  },
  "Styracosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/StyracosaurCMN2.jpg/960px-StyracosaurCMN2.jpg",
    "short": "Styracosaurus is an extinct genus of herbivorous dinosaur from the Late Cretaceous of North America.",
    "full": "It had four to six long parietal spikes extending from its neck frill, a smaller jugal horn on each of its cheeks, and a single horn protruding from its nose, which may have been up to 60 centimeters long and 15 centimeters wide. The function or functions of the horns and frills have been debated for many years."
  },
  "Therizinosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Therizinosaurus_arms.jpg/960px-Therizinosaurus_arms.jpg",
    "short": "Therizinosaurus is a genus of very large therizinosaurid dinosaurs that lived during the Late Cretaceous period in what is now Asia.",
    "full": "It contains a single species, Therizinosaurus cheloniformis, known from the fossiliferous Nemegt Formation. The first remains of Therizinosaurus were found in 1948 by a Mongolian field expedition in the Gobi Desert and later described by Evgeny Maleev in 1954. The genus is only known from a few bones, including gigantic manual unguals, from which it gets its name, and additional findings comprising fore and hindlimb elements that were discovered from the 1960s through the 1980s."
  },
  "Gorgosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Drumheller_150.jpg/960px-Drumheller_150.jpg",
    "short": "Gorgosaurus is a genus of tyrannosaurid theropod dinosaur that lived in western North America during the Late Cretaceous Period (Campanian), between about 76.5 and 75 million years ago.",
    "full": "Fossil remains have been found in the Canadian province of Alberta and the U.S. state of Montana. Paleontologists recognize only the type species, G. libratus, although other species have been erroneously referred to the genus."
  },
  "Amargasaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Amargasaurus_in_Prague_National_Museum.jpg/960px-Amargasaurus_in_Prague_National_Museum.jpg",
    "short": "Amargasaurus is a genus of sauropod dinosaur from the Early Cretaceous epoch of what is now Argentina.",
    "full": "The only known skeleton was discovered in 1984 and is virtually complete, including a fragmentary skull, making Amargasaurus one of the best-known sauropods of its epoch. Amargasaurus was first described in 1991 and contains a single known species, Amargasaurus cazaui. It was a large animal, but small for a sauropod, reaching 9 to 13 meters in length. Most distinctively, it sported two parallel rows of tall spines down its neck and back, taller than in any other known sauropod. In life, these spines could have stuck out of the body as solitary structures that supported a keratinous sheath. An alternate hypothesis, now more favored, postulates that they could have formed a scaffold supporting a skin sail. They might have been used for display, combat, or defense."
  },
  "Euoplocephalus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Euoplocephalus_TMP_1991.127.1.tif/lossy-page1-960px-Euoplocephalus_TMP_1991.127.1.tif.jpg",
    "short": "Euoplocephalus is a genus of large herbivorous ankylosaurid dinosaurs, living during the Late Cretaceous of Canada.",
    "full": "It has only one named species, Euoplocephalus tutus."
  },
  "Pachyrhinosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Pachyrhinosaurus_Royal_Tyrrell_1.jpg/960px-Pachyrhinosaurus_Royal_Tyrrell_1.jpg",
    "short": "Pachyrhinosaurus is a genus of centrosaurine ceratopsid dinosaur from the Late Cretaceous period of North America.",
    "full": "The first examples were discovered by Charles M. Sternberg in Alberta, Canada, in 1946, and named in 1950. Over a dozen partial skulls and a large assortment of other fossils from various species have been found in Alberta and Alaska. A great number were not available for study until the 1980s, resulting in a relatively recent increase of interest in Pachyrhinosaurus."
  },
  "Lambeosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Lambeosaurus_Pacific_Museum_of_Earth.jpg/960px-Lambeosaurus_Pacific_Museum_of_Earth.jpg",
    "short": "Lambeosaurus is a genus of hadrosaurid dinosaur that lived during the Late Cretaceous period of western North America.",
    "full": "The first skull of Lambeosaurus found was used by palaeontologist Lawrence M. Lambe to justify the creation of the new genus Stephanosaurus, although it was not part of the latter's original material. Its incomplete nature led William A. Parks to name Lambeosaurus lambei for this skull in 1923 to honour Lambe. Multiple species of Lambeosaurus have been named since, including L. clavinitialis and L. magnicristatus in 1935, and L. laticaudus in 1981 which was later moved to its own genus Magnapaulia. It has also been identified that some species earlier identified as belonging to Tetragonosaurus and Corythosaurus are now considered juveniles of Lambeosaurus. It is the eponymous member of the subfamily Lambeosaurinae and tribe Lambeosaurini. Lambeosaurins, which also includes Corythosaurus and Hypacrosaurus from western North America, are understood to be some of the most specialized ornithopods."
  },
  "Albertosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Albertosaurus_sarcophagus_cast.jpg/960px-Albertosaurus_sarcophagus_cast.jpg",
    "short": "Albertosaurus is a genus of large tyrannosaurid theropod dinosaur that lived in northwestern North America during the early to middle Maastrichtian age of the Late Cretaceous period, about 71 million years ago.",
    "full": "The type species, A. sarcophagus, was apparently restricted in range to the modern-day Canadian province of Alberta, after which the genus is named, although an indeterminate species has been discovered in the Corral de Enmedio and Packard Formations of Mexico. Scientists disagree on the content of the genus and some recognize Gorgosaurus libratus as a second species."
  },
  "Pentaceratops": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Pentaceratops_sternbergii_holotype_AMNH6325.jpg/960px-Pentaceratops_sternbergii_holotype_AMNH6325.jpg",
    "short": "Pentaceratops is a genus of herbivorous ceratopsid dinosaur from the late Cretaceous Period of what is now North America.",
    "full": "Fossils of this animal were first discovered in 1921, but the genus was named in 1923 when its type species, Pentaceratops sternbergii, was described. Pentaceratops lived around 76–73 million years ago, its remains having been mostly found in the Kirtland Formation in the San Juan Basin in New Mexico. Another species, P. aquilonius, was named by Nick W. Longrich in 2014, but it is debated if it belongs to that genus or a separate taxon. About a dozen skulls and skeletons have been uncovered, so anatomical understanding of Pentaceratops is fairly complete. One exceptionally large specimen later became its own genus, Titanoceratops, due to its more derived morphology, similarities to Triceratops, and lack of unique characteristics shared with Pentaceratops."
  },
  "Anchiceratops": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Anchiceratops_UMMNH.jpg/960px-Anchiceratops_UMMNH.jpg",
    "short": "Anchiceratops is an extinct genus of chasmosaurine ceratopsid dinosaur that lived approximately 73 to 68 million years ago during the latter part of the Cretaceous Period in what is now Alberta, Canada.",
    "full": "Anchiceratops was a medium-sized, heavily built, ground-dwelling, quadrupedal herbivore that could grow up to an estimated 4.3 metres (14 ft) long. Its skull featured two long brow horns and a short horn on the nose. The skull frill was elongated and rectangular, its edges adorned by coarse triangular projections. About a dozen skulls of the genus have been found."
  },
  "Irritator": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Irritator_challengeri_mount_01.jpg/960px-Irritator_challengeri_mount_01.jpg",
    "short": "Irritator is a genus of spinosaurid dinosaur that lived in what is now Brazil during the Albian stage of the Early Cretaceous Period, about 113 to 110 million years ago.",
    "full": "It is known from a nearly complete skull found in the Romualdo Formation of the Araripe Basin. Fossil dealers had acquired this skull and sold it to the State Museum of Natural History Stuttgart. In 1996, the specimen became the holotype of the type species Irritator challengeri. The genus name comes from the word \"irritation\", reflecting the feelings of paleontologists who found the skull had been heavily damaged and altered by the collectors. The species name is a homage to the fictional character Professor Challenger from Arthur Conan Doyle's novels."
  },
  "Scelidosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Scelidosaurus_harrisonii_%281%29.jpg/960px-Scelidosaurus_harrisonii_%281%29.jpg",
    "short": "Scelidosaurus is a genus of herbivorous armoured ornithischian dinosaur from the Jurassic of England.",
    "full": ""
  },
  "Tsintaosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Tsintaosaurus_nasal.png/960px-Tsintaosaurus_nasal.png",
    "short": "Tsintaosaurus is a genus of hadrosaurid dinosaur from the Late Cretaceous of China.",
    "full": "It was about 8.3 metres (27 ft) long and weighed 2.5 tonnes. The type species is Tsintaosaurus spinorhinus, first described by Chinese paleontologist C. C. Young in 1958. As a hadrosaur, Tsintaosaurus had the characteristic 'duck bill' snout and a battery of powerful teeth which it used to chew vegetation. It usually walked on all fours, but could rear up on its hind legs to scout for predators and flee when it spotted one. Like other hadrosaurs, Tsintaosaurus probably lived and traveled in herds."
  },
  "Argentinosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Argentinosaurus_skeleton%2C_PLoS_ONE.png/960px-Argentinosaurus_skeleton%2C_PLoS_ONE.png",
    "short": "Argentinosaurus is a genus of giant sauropod dinosaur that lived during the Late Cretaceous period in what is now Argentina.",
    "full": "Although it is only known from fragmentary remains, Argentinosaurus is one of the largest known land animals of all time, perhaps the largest, measuring 30–35 m (98–115 ft) long and weighing 65–80 t. It was a member of Titanosauria, the dominant group of sauropods during the Cretaceous."
  },
  "Quetzalcoatlus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Quetzalcoatlus_northropi.jpg/960px-Quetzalcoatlus_northropi.jpg",
    "short": "Quetzalcoatlus is a genus of azhdarchid pterosaur that lived during the Maastrichtian age of the Late Cretaceous in North America.",
    "full": "The type specimen, recovered in 1971 from the Javelina Formation of Texas, United States, consists of several wing fragments and was described as Quetzalcoatlus northropi in 1975 by Douglas Lawson. The generic name refers to the Aztec serpent god of the sky, Quetzalcōātl, while the specific name honors Jack Northrop, designer of a tailless fixed-wing aircraft. The remains of a second species were found between 1972 and 1974, also by Lawson, around 40 km (25 mi) from the Q. northropi locality. In 2021, these remains were assigned to the name Quetzalcoatlus lawsoni by Brian Andres and (posthumously) Wann Langston Jr., as part of a series of publications on the genus."
  },
  "Microraptor": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Microraptor_gui_holotype.png/960px-Microraptor_gui_holotype.png",
    "short": "Microraptor is a genus of small, four-winged dromaeosaurid dinosaurs.",
    "full": "Numerous well-preserved fossil specimens have been recovered from Liaoning, China. They date from the early Cretaceous Jiufotang Formation, 125 to 120 million years ago. Three species have been named, though further study has suggested that all of them represent variation in a single species, which is properly called M. zhaoianus. Cryptovolans, initially described as another four-winged dinosaur, is usually considered to be a synonym of Microraptor."
  },
  "Giganotosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Giganotosaurus_at_Fernbank.jpg/960px-Giganotosaurus_at_Fernbank.jpg",
    "short": "Giganotosaurus is a genus of large theropod dinosaur that lived in what is now Argentina, during the early Cenomanian age of the Late Cretaceous period, approximately 99.6 to 95 million years ago.",
    "full": "The holotype specimen was discovered in the Candeleros Formation of Patagonia in 1993 and is almost 70% complete. The animal was named Giganotosaurus carolinii in 1995; the genus name translates to \"giant southern lizard\", and the specific name honors the discoverer, Ruben Carolini. A dentary bone, a tooth, and some tracks, discovered before the holotype, were later assigned to this animal. The genus attracted much interest and became part of a scientific debate about the maximum sizes of theropod dinosaurs."
  },
  "Eoraptor": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Eoraptor_Japan.jpg/960px-Eoraptor_Japan.jpg",
    "short": "Eoraptor is a genus of small, lightly built, basal sauropodomorph dinosaur.",
    "full": "One of the earliest-known dinosaurs and one of the earliest sauropodomorphs, it lived approximately 231 to 228 million years ago, during the Late Triassic in Western Gondwana, in the region that is now northwestern Argentina. The type and only species, Eoraptor lunensis, was first described in 1993, and is known from an almost complete and well-preserved skeleton and several fragmentary ones. Eoraptor had multiple tooth shapes, which suggests that it was omnivorous."
  },
  "Sauroposeidon": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Sauroposeidon_proteles_Skeletal.png/960px-Sauroposeidon_proteles_Skeletal.png",
    "short": "Sauroposeidon is a genus of sauropod dinosaur known from several incomplete specimens including a bone bed and fossilized trackways that have been found in the U.S. states of Oklahoma, Wyoming, and Texas.",
    "full": ""
  },
  "Sinosauropteryx": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Sinosauropteryxfossil.jpg/960px-Sinosauropteryxfossil.jpg",
    "short": "Sinosauropteryx is an extinct genus of coelurosaurian theropod dinosaurs.",
    "full": "Described in 1996, it was the first dinosaur taxon outside of Avialae to be found with evidence of feathers. It was covered with a coat of very simple filament-like feathers. Structures that indicate the colour pattern have also been preserved in some of its feathers, which show that Sinosauropteryx had a countershading pattern in its body with a banded tail. The reddish brown colouration previously inferred for Sinosauropteryx is based on the melanosomes preserved in the specimen of a separate genus, Huadanosaurus. Some contention has arisen with an alternative interpretation of the filamentous impression as remains of collagen fibres, but this has not been widely accepted."
  },
  "Herrerasaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Herrerasaurus_skeleton.jpg/960px-Herrerasaurus_skeleton.jpg",
    "short": "Herrerasaurus is likely a genus of saurischian dinosaur from the Late Triassic period.",
    "full": "Measuring 6 m (20 ft) long and weighing around 350 kg (770 lb), this genus was one of the earliest dinosaurs from the fossil record. Its name means \"Herrera's lizard\", after the rancher who discovered the first specimen in 1958 in South America. All known fossils of this carnivore have been discovered in the Ischigualasto Formation of Carnian age in northwestern Argentina. The type species, Herrerasaurus ischigualastensis, was described by Osvaldo Reig in 1963 and is the only species assigned to the genus. Ischisaurus and Frenguellisaurus are synonyms."
  },
  "Dracorex": {
    "img": "",
    "short": "Pachycephalosaurus is a genus of pachycephalosaurid ornithischian dinosaur.",
    "full": "The type species, P. wyomingensis, is the only known definitive species. The possibly synonymous taxon, Stygimoloch, might represent a distinct genus or a second species, P. spinifer. It lived during the Maastrichtian age of the Late Cretaceous period in what is now western North America. Remains have been excavated in Montana, South Dakota, Wyoming, and Alberta. Mainly known from a single skull and a few extremely thick skull roofs, Pachycephalosaurus is estimated to have reached 4.5 m (15 ft) long and weighed 370–450 kg (820–990 lb). More complete fossils would come to be found in the following years."
  },
  "Nothronychus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Therizinosauridae_Diversity.jpg/960px-Therizinosauridae_Diversity.jpg",
    "short": "Nothronychus is a genus of therizinosaurid theropod dinosaurs that lived in North America during the Late Cretaceous period.",
    "full": "The type species, Nothronychus mckinleyi, was described by James Kirkland and Douglas G. Wolfe in 2001. It was recovered near New Mexico's border with Arizona, in an area known as the Zuni Basin, from rocks assigned to the Moreno Hill Formation, dating to the Turonian stage of the Late Cretaceous. A second specimen, described in 2009 as a second species, Nothronychus graffami, was found in the Tropic Shale of Utah, dating to between one million and 500,000 years older than N. mckinleyi."
  },
  "Magyarosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Titanosaur_remains_used_to_erect_Magyarosaurus_dacus.jpg/960px-Titanosaur_remains_used_to_erect_Magyarosaurus_dacus.jpg",
    "short": "Magyarosaurus is a genus of dwarf sauropod dinosaur from late Cretaceous Period in today's Transylvania.",
    "full": "It is one of the smallest-known adult sauropods, measuring less than 3 m (9.8 ft) long and weighing less than 1,000 kg (2,200 lb). The type and only species is Magyarosaurus dacus. It has been found to be a close relative of Rapetosaurus in the family Saltasauridae in the sauropod clade Titanosauria in a 2005 study."
  },
  "Abrictosaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Abrictosaurus.jpg/960px-Abrictosaurus.jpg",
    "short": "Abrictosaurus is a genus of heterodontosaurid dinosaur that lived during the Early Jurassic in what is now in parts of southern Africa such as Lesotho and South Africa.",
    "full": "It was a bipedal herbivore or omnivore and was one of the most basal heterodontosaurids. It was approximately 1.2 metres (3.9 ft) long and weighed less than 45 kilograms (99 lb)."
  },
  "Yinlong": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/%E6%98%8C%E5%90%89%E6%81%90%E9%BE%99%E9%A6%86_%E5%BD%93%E6%B0%8F%E9%9A%90%E9%BE%99%EF%BC%88Yinlong_downsi%EF%BC%89.jpg/960px-%E6%98%8C%E5%90%89%E6%81%90%E9%BE%99%E9%A6%86_%E5%BD%93%E6%B0%8F%E9%9A%90%E9%BE%99%EF%BC%88Yinlong_downsi%EF%BC%89.jpg",
    "short": "Yinlong is a genus of basal ceratopsian dinosaur from the Late Jurassic Period of China.",
    "full": "By far the earliest known ceratopsian, it was a small, primarily bipedal herbivore."
  },
  "Limusaurus": {
    "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Limusaurus_inextricabilis_skeleton.jpg/960px-Limusaurus_inextricabilis_skeleton.jpg",
    "short": "Limusaurus is a genus of theropod dinosaur that lived in what is now China during the Late Jurassic, around 161 to 157 million years ago.",
    "full": "The type and only species Limusaurus inextricabilis was described in 2009 from specimens found in the Upper Shishugou Formation in the Junggar Basin of China. The genus name consists of the Latin words for \"mud\" and \"lizard\", and the species name means \"impossible to extricate\", both referring to these specimens possibly dying after being mired. Limusaurus was a small, slender animal, about 1.7 m in length and 15 kg (33 lb) in weight, which had a long neck and legs but very small forelimbs. It underwent a drastic morphological transformation as it aged: while juveniles were toothed, these teeth were completely lost and replaced by a beak with age. Several of these features were convergently similar to the later ornithomimid theropods as well as the earlier non-dinosaurian shuvosaurids."
  }
};
