// Dino data: name, wiki article title, difficulty level (1-5), length in metres.
// Facts are fetched live from the Wikipedia summary API — nothing hardcoded here.
const DINOS = [
  // ── Level 1 – Super Famous ────────────────────────────────────────────────
  { name: "Tyrannosaurus Rex",    wiki: "Tyrannosaurus",        level: 1, length: 12,   period: "Late Cretaceous (68–66 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Triceratops",          wiki: "Triceratops",          level: 1, length: 9,    period: "Late Cretaceous (68–66 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Stegosaurus",          wiki: "Stegosaurus",          level: 1, length: 9,    period: "Late Jurassic (155–150 Ma)",    diet: "Herbivore",   geo: "North America, Europe" },
  { name: "Brachiosaurus",        wiki: "Brachiosaurus",        level: 1, length: 26,   period: "Late Jurassic (154–153 Ma)",    diet: "Herbivore",   geo: "North America, Africa" },
  { name: "Velociraptor",         wiki: "Velociraptor",         level: 1, length: 2,    period: "Late Cretaceous (75–71 Ma)",    diet: "Carnivore",   geo: "Asia"                  },
  { name: "Ankylosaurus",         wiki: "Ankylosaurus",         level: 1, length: 10,   period: "Late Cretaceous (68–66 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Diplodocus",           wiki: "Diplodocus",           level: 1, length: 27,   period: "Late Jurassic (154–152 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Spinosaurus",          wiki: "Spinosaurus",          level: 1, length: 15,   period: "Cretaceous (99–93 Ma)",         diet: "Piscivore",   geo: "North Africa"          },
  { name: "Pteranodon",           wiki: "Pteranodon",           level: 1, length: 1.8,  period: "Late Cretaceous (86–84 Ma)",    diet: "Piscivore",   geo: "North America"         },
  { name: "Apatosaurus",          wiki: "Apatosaurus",          level: 1, length: 23,   period: "Late Jurassic (154–150 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Allosaurus",           wiki: "Allosaurus",           level: 1, length: 12,   period: "Late Jurassic (155–145 Ma)",    diet: "Carnivore",   geo: "North America, Europe" },
  { name: "Iguanodon",            wiki: "Iguanodon",            level: 1, length: 10,   period: "Early Cretaceous (126–113 Ma)", diet: "Herbivore",   geo: "Europe, North America" },

  // ── Level 2 – Well Known ──────────────────────────────────────────────────
  { name: "Parasaurolophus",      wiki: "Parasaurolophus",      level: 2, length: 10,   period: "Late Cretaceous (76–73 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Pachycephalosaurus",   wiki: "Pachycephalosaurus",   level: 2, length: 5,    period: "Late Cretaceous (70–66 Ma)",    diet: "Omnivore",    geo: "North America"         },
  { name: "Carnotaurus",          wiki: "Carnotaurus",          level: 2, length: 9,    period: "Late Cretaceous (72–69 Ma)",    diet: "Carnivore",   geo: "South America"         },
  { name: "Dilophosaurus",        wiki: "Dilophosaurus",        level: 2, length: 6,    period: "Early Jurassic (~193 Ma)",      diet: "Carnivore",   geo: "North America"         },
  { name: "Gallimimus",           wiki: "Gallimimus",           level: 2, length: 6,    period: "Late Cretaceous (~70 Ma)",      diet: "Omnivore",    geo: "Asia"                  },
  { name: "Mosasaurus",           wiki: "Mosasaurus",           level: 2, length: 17,   period: "Late Cretaceous (82–66 Ma)",    diet: "Carnivore",   geo: "Worldwide (oceans)"    },
  { name: "Archaeopteryx",        wiki: "Archaeopteryx",        level: 2, length: 0.5,  period: "Late Jurassic (~150 Ma)",       diet: "Carnivore",   geo: "Europe"                },
  { name: "Edmontosaurus",        wiki: "Edmontosaurus",        level: 2, length: 13,   period: "Late Cretaceous (73–66 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Deinonychus",          wiki: "Deinonychus",          level: 2, length: 3.4,  period: "Early Cretaceous (115–108 Ma)", diet: "Carnivore",   geo: "North America"         },
  { name: "Coelophysis",          wiki: "Coelophysis",          level: 2, length: 3,    period: "Late Triassic (213–203 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Troodon",              wiki: "Troodon",              level: 2, length: 2.4,  period: "Late Cretaceous (77–66 Ma)",    diet: "Omnivore",    geo: "North America"         },
  { name: "Utahraptor",           wiki: "Utahraptor",           level: 2, length: 6,    period: "Early Cretaceous (~126 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Corythosaurus",        wiki: "Corythosaurus",        level: 2, length: 9,    period: "Late Cretaceous (77–75 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Plateosaurus",         wiki: "Plateosaurus",         level: 2, length: 8,    period: "Late Triassic (214–204 Ma)",    diet: "Herbivore",   geo: "Europe"                },

  // ── Level 3 – Intermediate ────────────────────────────────────────────────
  { name: "Baryonyx",             wiki: "Baryonyx",             level: 3, length: 10,   period: "Early Cretaceous (130–125 Ma)", diet: "Piscivore",   geo: "Europe"                },
  { name: "Ceratosaurus",         wiki: "Ceratosaurus",         level: 3, length: 6,    period: "Late Jurassic (153–148 Ma)",    diet: "Carnivore",   geo: "North America, Africa" },
  { name: "Maiasaura",            wiki: "Maiasaura",            level: 3, length: 9,    period: "Late Cretaceous (77–75 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Oviraptor",            wiki: "Oviraptor",            level: 3, length: 2,    period: "Late Cretaceous (75–71 Ma)",    diet: "Omnivore",    geo: "Asia"                  },
  { name: "Carcharodontosaurus",  wiki: "Carcharodontosaurus",  level: 3, length: 13,   period: "Cretaceous (99–94 Ma)",         diet: "Carnivore",   geo: "North Africa"          },
  { name: "Suchomimus",           wiki: "Suchomimus",           level: 3, length: 11,   period: "Early Cretaceous (~112 Ma)",    diet: "Piscivore",   geo: "Africa"                },
  { name: "Kentrosaurus",         wiki: "Kentrosaurus",         level: 3, length: 4.5,  period: "Late Jurassic (156–150 Ma)",    diet: "Herbivore",   geo: "Africa"                },
  { name: "Protoceratops",        wiki: "Protoceratops",        level: 3, length: 1.8,  period: "Late Cretaceous (75–71 Ma)",    diet: "Herbivore",   geo: "Asia"                  },
  { name: "Camarasaurus",         wiki: "Camarasaurus",         level: 3, length: 18,   period: "Late Jurassic (155–145 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Camptosaurus",         wiki: "Camptosaurus",         level: 3, length: 7,    period: "Late Jurassic (155–145 Ma)",    diet: "Herbivore",   geo: "North America, Europe" },
  { name: "Ouranosaurus",         wiki: "Ouranosaurus",         level: 3, length: 8,    period: "Early Cretaceous (~112 Ma)",    diet: "Herbivore",   geo: "Africa"                },
  { name: "Psittacosaurus",       wiki: "Psittacosaurus",       level: 3, length: 2,    period: "Early Cretaceous (126–101 Ma)", diet: "Herbivore",   geo: "Asia"                  },
  { name: "Saurolophus",          wiki: "Saurolophus",          level: 3, length: 9,    period: "Late Cretaceous (70–68 Ma)",    diet: "Herbivore",   geo: "North America, Asia"   },
  { name: "Megaraptor",           wiki: "Megaraptor",           level: 3, length: 8,    period: "Late Cretaceous (~90 Ma)",      diet: "Carnivore",   geo: "South America"         },
  { name: "Concavenator",         wiki: "Concavenator",         level: 3, length: 6,    period: "Early Cretaceous (~130 Ma)",    diet: "Carnivore",   geo: "Europe"                },

  // ── Level 4 – Advanced ────────────────────────────────────────────────────
  { name: "Styracosaurus",        wiki: "Styracosaurus",        level: 4, length: 5.5,  period: "Late Cretaceous (75–74 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Therizinosaurus",      wiki: "Therizinosaurus",      level: 4, length: 10,   period: "Late Cretaceous (~70 Ma)",      diet: "Herbivore",   geo: "Asia"                  },
  { name: "Gorgosaurus",          wiki: "Gorgosaurus",          level: 4, length: 9,    period: "Late Cretaceous (76–74 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Amargasaurus",         wiki: "Amargasaurus",         level: 4, length: 10,   period: "Early Cretaceous (130–125 Ma)", diet: "Herbivore",   geo: "South America"         },
  { name: "Euoplocephalus",       wiki: "Euoplocephalus",       level: 4, length: 6,    period: "Late Cretaceous (76–74 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Pachyrhinosaurus",     wiki: "Pachyrhinosaurus",     level: 4, length: 8,    period: "Late Cretaceous (73–69 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Lambeosaurus",         wiki: "Lambeosaurus",         level: 4, length: 9,    period: "Late Cretaceous (76–75 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Albertosaurus",        wiki: "Albertosaurus",        level: 4, length: 9,    period: "Late Cretaceous (73–70 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Pentaceratops",        wiki: "Pentaceratops",        level: 4, length: 8,    period: "Late Cretaceous (76–73 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Anchiceratops",        wiki: "Anchiceratops",        level: 4, length: 6,    period: "Late Cretaceous (72–71 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Irritator",            wiki: "Irritator",            level: 4, length: 8,    period: "Early Cretaceous (~110 Ma)",    diet: "Piscivore",   geo: "South America"         },
  { name: "Scelidosaurus",        wiki: "Scelidosaurus",        level: 4, length: 4,    period: "Early Jurassic (196–183 Ma)",   diet: "Herbivore",   geo: "Europe"                },
  { name: "Tsintaosaurus",        wiki: "Tsintaosaurus",        level: 4, length: 8,    period: "Late Cretaceous (84–71 Ma)",    diet: "Herbivore",   geo: "Asia"                  },

  // ── Level 5 – Expert ──────────────────────────────────────────────────────
  { name: "Argentinosaurus",      wiki: "Argentinosaurus",      level: 5, length: 35,   period: "Late Cretaceous (96–93 Ma)",    diet: "Herbivore",   geo: "South America"         },
  { name: "Quetzalcoatlus",       wiki: "Quetzalcoatlus",       level: 5, length: 3,    period: "Late Cretaceous (68–66 Ma)",    diet: "Carnivore",   geo: "North America"         },
  { name: "Microraptor",          wiki: "Microraptor",          level: 5, length: 0.8,  period: "Early Cretaceous (125–120 Ma)", diet: "Carnivore",   geo: "Asia"                  },
  { name: "Giganotosaurus",       wiki: "Giganotosaurus",       level: 5, length: 13,   period: "Late Cretaceous (99–95 Ma)",    diet: "Carnivore",   geo: "South America"         },
  { name: "Eoraptor",             wiki: "Eoraptor",             level: 5, length: 1,    period: "Late Triassic (~231 Ma)",       diet: "Omnivore",    geo: "South America"         },
  { name: "Sauroposeidon",        wiki: "Sauroposeidon",        level: 5, length: 34,   period: "Early Cretaceous (~110 Ma)",    diet: "Herbivore",   geo: "North America"         },
  { name: "Sinosauropteryx",      wiki: "Sinosauropteryx",      level: 5, length: 1,    period: "Early Cretaceous (~125 Ma)",    diet: "Carnivore",   geo: "Asia"                  },
  { name: "Herrerasaurus",        wiki: "Herrerasaurus",        level: 5, length: 4.5,  period: "Late Triassic (~231 Ma)",       diet: "Carnivore",   geo: "South America"         },
  { name: "Dracorex",             wiki: "Dracorex",             level: 5, length: 3,    period: "Late Cretaceous (~66 Ma)",      diet: "Herbivore",   geo: "North America"         },
  { name: "Nothronychus",         wiki: "Nothronychus",         level: 5, length: 4.5,  period: "Late Cretaceous (~91 Ma)",      diet: "Herbivore",   geo: "North America"         },
  { name: "Magyarosaurus",        wiki: "Magyarosaurus",        level: 5, length: 6,    period: "Late Cretaceous (70–66 Ma)",    diet: "Herbivore",   geo: "Europe"                },
  { name: "Abrictosaurus",        wiki: "Abrictosaurus",        level: 5, length: 1.2,  period: "Early Jurassic (200–190 Ma)",   diet: "Herbivore",   geo: "Africa"                },
  { name: "Yinlong",              wiki: "Yinlong",              level: 5, length: 1.2,  period: "Late Jurassic (161–157 Ma)",    diet: "Omnivore",    geo: "Asia"                  },
  { name: "Limusaurus",           wiki: "Limusaurus",           level: 5, length: 1.7,  period: "Late Jurassic (163–145 Ma)",    diet: "Herbivore",   geo: "Asia"                  },
];
