// ── Bundled data (from dino-data.js, generated by make fetch-data) ────────────
// Pre-populate caches so no Wikipedia API calls are needed at runtime.
const imageCache = {};
const factCache = {};

if (typeof DINO_DATA !== 'undefined') {
  for (const [wiki, data] of Object.entries(DINO_DATA)) {
    if (data.img)   imageCache[wiki] = data.img;
    if (data.short) factCache[wiki]  = { short: data.short, full: data.full || '' };
  }
}

async function fetchWikiImage(wikiTitle) {
  if (imageCache[wikiTitle]) return imageCache[wikiTitle];
  try {
    const url = `https://en.wikipedia.org/w/api.php?action=query&titles=${encodeURIComponent(wikiTitle)}&prop=pageimages&format=json&pithumbsize=500&origin=*`;
    const res = await fetch(url);
    const data = await res.json();
    const page = Object.values(data.query.pages)[0];
    const src = page?.thumbnail?.source || null;
    imageCache[wikiTitle] = src;
    return src;
  } catch {
    imageCache[wikiTitle] = null;
    return null;
  }
}

async function preloadImages(dinos) {
  await Promise.all(dinos.map(d => fetchWikiImage(d.wiki)));
}

// ── Fact cache (Wikipedia summary API) ───────────────────────────────────────
async function fetchWikiFact(wikiTitle) {
  if (factCache[wikiTitle] !== undefined) return factCache[wikiTitle];
  try {
    const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(wikiTitle)}`;
    const res = await fetch(url);
    const data = await res.json();
    const extract = data.extract || '';
    const firstMatch = extract.match(/[^.!?]*[.!?]/);
    const short = firstMatch?.[0]?.trim() || extract.slice(0, 160).trim();
    const full = firstMatch ? extract.slice(firstMatch[0].length).trim() : '';
    factCache[wikiTitle] = { short, full };
    return factCache[wikiTitle];
  } catch {
    factCache[wikiTitle] = { short: '', full: '' };
    return factCache[wikiTitle];
  }
}

async function preloadFacts(dinos) {
  await Promise.all(dinos.map(d => fetchWikiFact(d.wiki)));
}

// ── Keyboard navigation ───────────────────────────────────────────────────────
let focusedOptionIndex = -1;

function getOptionButtons() {
  return Array.from(document.querySelectorAll('#question-area [data-name]'));
}

function applyKeyboardFocus(buttons) {
  buttons.forEach((btn, i) => {
    btn.classList.toggle('keyboard-focus', i === focusedOptionIndex);
  });
  if (focusedOptionIndex === -1) {
    showKbCursor();
  } else {
    hideKbCursor();
  }
}

function resetKeyboardFocus() {
  focusedOptionIndex = -1;
  applyKeyboardFocus(getOptionButtons());
}

function showKbCursor() {
  document.querySelectorAll('.kb-cursor').forEach(el => el.remove());
  const firstBtn = getOptionButtons()[0];
  if (!firstBtn) return;
  const container = firstBtn.parentElement;
  container.style.position = 'relative';
  const cursor = document.createElement('div');
  cursor.className = 'kb-cursor';
  cursor.textContent = '▶';
  container.appendChild(cursor);
}

function hideKbCursor() {
  document.querySelectorAll('.kb-cursor').forEach(el => el.remove());
}

function jiggleKbCursor() {
  const cursor = document.querySelector('#question-area .kb-cursor');
  if (!cursor) return;
  cursor.classList.add('keyboard-jiggle');
  cursor.addEventListener('animationend', () => cursor.classList.remove('keyboard-jiggle'), { once: true });
}

// All question layouts use 2 columns
const GRID_COLS = 2;

function gridMove(index, direction, total) {
  const col = index % GRID_COLS;
  const row = Math.floor(index / GRID_COLS);
  const maxRow = Math.floor((total - 1) / GRID_COLS);

  if (direction === 'right' && col < GRID_COLS - 1 && index + 1 < total) return index + 1;
  if (direction === 'left'  && col > 0)                                   return index - 1;
  if (direction === 'down'  && row < maxRow && index + GRID_COLS < total) return index + GRID_COLS;
  if (direction === 'up'    && row > 0)                                   return index - GRID_COLS;
  return null;
}

function jiggleFocused(buttons) {
  const btn = buttons[focusedOptionIndex];
  if (!btn) return;
  btn.classList.add('keyboard-jiggle');
  btn.addEventListener('animationend', () => btn.classList.remove('keyboard-jiggle'), { once: true });
}

// ── Game state ────────────────────────────────────────────────────────────────
let state = {
  score: 0,
  streak: 0,
  questionNum: 0,
  totalQuestions: 10,
  pool: [],
  imageDinos: [], // subset with loaded images, for name-match / pic-match
  currentQ: null,
  answeredThisRound: false,
  usedCorrects: new Set(),
  results: [], // 'pending' | 'current' | 'correct' | 'wrong'
};

const SCORE_MULT = 1.5;

// Each question gets its mode from this rotating sequence
const MODE_SEQUENCE = [
  'name-match', 'size-battle', 'name-match', 'dino-facts',
  'name-match', 'pic-match',   'size-battle', 'name-match',
  'dino-facts', 'size-battle',
];

function buildPool() {
  return [...DINOS];
}

function pick(arr, n) {
  const copy = [...arr];
  const result = [];
  while (result.length < n && copy.length) {
    const i = Math.floor(Math.random() * copy.length);
    result.push(copy.splice(i, 1)[0]);
  }
  return result;
}

function calcPoints(correct) {
  if (!correct) return 0;
  const base = 100;
  const streakBonus = Math.min(state.streak * 10, 50);
  return Math.round((base + streakBonus) * SCORE_MULT);
}

// ── Question builders ─────────────────────────────────────────────────────────

function pickFreshCorrect() {
  const fresh = state.pool.filter(d => !state.usedCorrects.has(d.name));
  const candidates = fresh.length >= 1 ? fresh : state.pool; // fallback if pool exhausted
  const [correct] = pick(candidates, 1);
  state.usedCorrects.add(correct.name);
  return correct;
}

function buildNameMatchQuestion() {
  const imgPool = state.imageDinos;
  const correct = pick(imgPool.filter(d => !state.usedCorrects.has(d.name)), 1)[0]
    || pick(imgPool, 1)[0];
  state.usedCorrects.add(correct.name);
  const wrongs = pick(imgPool.filter(d => d.name !== correct.name), 3);
  const options = pick([correct, ...wrongs], 4); // shuffled
  return { type: 'name-match', correct, options, imgSrc: imageCache[correct.wiki] };
}

function buildPicMatchQuestion() {
  const imgPool = state.imageDinos;
  const correct = pick(imgPool.filter(d => !state.usedCorrects.has(d.name)), 1)[0]
    || pick(imgPool, 1)[0];
  state.usedCorrects.add(correct.name);
  const wrongs = pick(imgPool.filter(d => d.name !== correct.name), 3);
  const options = pick([correct, ...wrongs], 4);
  return { type: 'pic-match', correct, options };
}

function buildSizeBattleQuestion() {
  const fresh = state.pool.filter(d => !state.usedCorrects.has(d.name));
  const [a, b] = pick(fresh.length >= 2 ? fresh : state.pool, 2);
  state.usedCorrects.add(a.name);
  state.usedCorrects.add(b.name);
  const bigger = a.length >= b.length ? a : b;
  return { type: 'size-battle', a, b, bigger };
}

function buildDinoFactsQuestion() {
  const correct = pickFreshCorrect();
  const wrongs = pick(state.pool.filter(d => d.name !== correct.name), 3);
  const options = pick([correct, ...wrongs], 4);
  const cached = factCache[correct.wiki] || { short: 'A fascinating dinosaur!', full: '' };
  const rawFact = cached.short || 'A fascinating dinosaur!';
  // Scrub the dino's name (and each word of it) from the clue so it isn't a giveaway
  const nameParts = [correct.name, ...correct.name.split(/\s+/)].filter(p => p.length > 3);
  const pattern = new RegExp(nameParts.map(p => p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|'), 'gi');
  const fact = rawFact.replace(pattern, '___');
  return { type: 'dino-facts', correct, options, fact };
}

async function nextQuestion() {
  state.answeredThisRound = false;
  state.questionNum++;
  state.results[state.questionNum - 1] = 'current';
  updateProgressTrack();

  const mode = MODE_SEQUENCE[(state.questionNum - 1) % MODE_SEQUENCE.length];
  let q;
  switch (mode) {
    case 'name-match':  q = buildNameMatchQuestion(); break;
    case 'pic-match':   q = buildPicMatchQuestion();  break;
    case 'size-battle': q = buildSizeBattleQuestion(); break;
    case 'dino-facts':  q = buildDinoFactsQuestion();  break;
  }
  state.currentQ = q;
  await renderQuestion(q);
}

// ── Game flow ─────────────────────────────────────────────────────────────────

async function startGame() {
  state.score = 0;
  state.streak = 0;
  state.questionNum = 0;
  state.pool = buildPool();
  state.usedCorrects = new Set();

  showScreen('screen-loading');
  setLoadingMessage('Fetching dinosaur images & facts...');

  await Promise.all([preloadImages(state.pool), preloadFacts(state.pool)]);
  // name-match and pic-match need images; size-battle and dino-facts don't
  const imageDinos = state.pool.filter(d => imageCache[d.wiki]);
  if (imageDinos.length < 4) {
    alert('Could not load enough dinosaur images. Check your connection!');
    showScreen('screen-title');
    return;
  }
  state.imageDinos = imageDinos;

  state.results = Array(state.totalQuestions).fill('pending');
  showScreen('screen-game');
  updateHUD();
  updateProgressTrack();
  await nextQuestion();
}

async function handleAnswer(chosen) {
  if (state.answeredThisRound) return;
  state.answeredThisRound = true;

  const q = state.currentQ;
  let correct = false;

  if (q.type === 'name-match' || q.type === 'dino-facts') {
    correct = chosen.name === q.correct.name;
  } else if (q.type === 'pic-match') {
    correct = chosen.name === q.correct.name;
  } else if (q.type === 'size-battle') {
    correct = chosen.name === q.bigger.name;
  }

  if (correct) {
    state.streak++;
    const pts = calcPoints(true);
    state.score += pts;
    state.results[state.questionNum - 1] = 'correct';
    showAnswerView(true, pts, q);
  } else {
    state.streak = 0;
    state.results[state.questionNum - 1] = 'wrong';
    showAnswerView(false, 0, q);
  }

  updateHUD();
  updateProgressTrack();

  await waitForAnswerDismiss();

  if (state.questionNum >= state.totalQuestions) {
    endGame();
  } else {
    await nextQuestion();
  }
}

function endGame() {
  showScreen('screen-gameover');
  document.getElementById('final-score').textContent = state.score;
  document.getElementById('final-mode').textContent = 'DinoQuest';

  const best = getLocalBest('dinoquest');
  const isHigh = state.score > best;
  document.getElementById('highscore-msg').textContent = isHigh
    ? '🏆 New Local High Score!'
    : `Local Best: ${best}`;

  document.getElementById('initials-input').value = '';
  document.getElementById('initials-error').textContent = '';
}

function submitScore() {
  const raw = document.getElementById('initials-input').value.toUpperCase().trim();
  if (!isValidInitials(raw)) {
    document.getElementById('initials-error').textContent =
      raw.length !== 3 ? 'Enter exactly 3 letters.' : 'Choose different initials!';
    return;
  }
  saveScore({ initials: raw, score: state.score, mode: 'dinoquest' });
  showHighScores('dinoquest');
}

// ── Render ────────────────────────────────────────────────────────────────────

function updateProgressTrack() {
  const boxes = document.getElementById('progress-boxes');
  if (!boxes) return;
  boxes.innerHTML = '';
  // Render reversed so question 1 is at the bottom, 10 at the top
  for (let i = state.totalQuestions - 1; i >= 0; i--) {
    const box = document.createElement('div');
    box.className = 'progress-box ' + (state.results[i] || 'pending');
    boxes.appendChild(box);
  }
}

function updateHUD() {
  document.getElementById('hud-score').textContent = state.score;
  if (state.streak >= 2) {
    document.getElementById('hud-streak').textContent = `🔥 x${state.streak}`;
  } else {
    document.getElementById('hud-streak').textContent = '';
  }
}

async function renderQuestion(q) {
  const area = document.getElementById('question-area');
  area.innerHTML = '';

  if (q.type === 'name-match') {
    area.innerHTML = `
      <p class="question-prompt">Which dinosaur is this?</p>
      <div class="dino-image-wrap">
        <img src="${q.imgSrc}" alt="mystery dinosaur" class="dino-img" onerror="this.src='img/dino-placeholder.svg'"/>
      </div>
      <div class="options grid-2">
        ${q.options.map(d => `
          <button class="option-btn" onclick="handleAnswer(DINOS.find(x=>x.name===this.dataset.name))" data-name="${d.name}">${d.name}</button>
        `).join('')}
      </div>`;
  } else if (q.type === 'pic-match') {
    // preload images for options
    await preloadImages(q.options);
    area.innerHTML = `
      <p class="question-prompt">Find the picture of: <strong>${q.correct.name}</strong></p>
      <div class="options grid-2 pic-grid">
        ${q.options.map(d => {
          const src = imageCache[d.wiki] || '';
          return `<button class="option-btn pic-btn" onclick="handleAnswer(DINOS.find(x=>x.name===this.dataset.name))" data-name="${d.name}">
            <img src="${src}" alt="${d.name}" onerror="this.src='img/dino-placeholder.svg'"/>
            </button>`;
        }).join('')}
      </div>`;
  } else if (q.type === 'size-battle') {
    const imgA = imageCache[q.a.wiki];
    const imgB = imageCache[q.b.wiki];
    area.innerHTML = `
      <p class="question-prompt">Which dinosaur was <strong>BIGGER</strong>?</p>
      <div class="size-battle-wrap">
        <button class="size-card" onclick="handleAnswer(DINOS.find(x=>x.name===this.dataset.name))" data-name="${q.a.name}">
          ${imgA ? `<img src="${imgA}" alt="${q.a.name}"/>` : '<div class="no-img">?</div>'}
          <span class="size-name">${q.a.name}</span>
        </button>
        <div class="vs-badge">VS</div>
        <button class="size-card" onclick="handleAnswer(DINOS.find(x=>x.name===this.dataset.name))" data-name="${q.b.name}">
          ${imgB ? `<img src="${imgB}" alt="${q.b.name}"/>` : '<div class="no-img">?</div>'}
          <span class="size-name">${q.b.name}</span>
        </button>
      </div>`;
  } else if (q.type === 'dino-facts') {
    area.innerHTML = `
      <p class="question-prompt">Which dinosaur is being described?</p>
      <div class="fact-box">"${q.fact}"</div>
      <div class="options grid-2">
        ${q.options.map(d => `
          <button class="option-btn" onclick="handleAnswer(DINOS.find(x=>x.name===this.dataset.name))" data-name="${d.name}">${d.name}</button>
        `).join('')}
      </div>`;
  }

  // Wire up button clicks properly (replace inline onclick with event listeners)
  area.querySelectorAll('[data-name]').forEach(btn => {
    btn.addEventListener('click', () => {
      const dino = DINOS.find(x => x.name === btn.dataset.name);
      if (dino) handleAnswer(dino);
    });
    // Remove inline onclick
    btn.removeAttribute('onclick');
  });

  resetKeyboardFocus();
}

function getSizeLevel(m) {
  if (m <  1)  return { level: 1, label: 'Tiny' };
  if (m <  4)  return { level: 2, label: 'Small' };
  if (m < 10)  return { level: 3, label: 'Medium' };
  if (m < 20)  return { level: 4, label: 'Large' };
  return              { level: 5, label: 'Enormous' };
}

function parseMidMa(period) {
  const m = period.match(/\(~?(\d+)(?:[–\-](\d+))?\s*Ma\)/);
  if (!m) return null;
  const a = parseInt(m[1]), b = m[2] ? parseInt(m[2]) : a;
  return (a + b) / 2;
}

function getGeoGlobes(geo) {
  const g = geo.toLowerCase();
  const out = new Set();
  if (g.includes('north america') || g.includes('south america')) out.add('🌎');
  if (g.includes('europe') || g.includes('africa'))               out.add('🌍');
  if (g.includes('asia'))                                          out.add('🌏');
  if (g.includes('ocean') || g.includes('worldwide'))             out.add('🌊');
  return [...out].join(' ');
}

function dinoInfoHTML(dino) {
  const ft = (dino.length * 3.281).toFixed(1);

  // ── Size-o-meter ──
  const { level, label: sizeLabel } = getSizeLevel(dino.length);
  const pips = Array.from({ length: 5 }, (_, i) =>
    `<span class="sizo-pip ${i < level ? 'on' : 'off'}"></span>`
  ).join('');

  // ── Period timeline ──
  // Triassic 252–201 Ma (51), Jurassic 201–145 Ma (56), Cretaceous 145–66 Ma (79). Total 186.
  const periodName  = dino.period.replace(/\s*\([^)]*\)/, '').trim();
  const periodDates = dino.period.match(/\(([^)]+)\)/)?.[1] ?? '';
  const midMa       = parseMidMa(dino.period) ?? 100;
  const markerPct   = Math.min(100, Math.max(0, (252 - midMa) / 186 * 100)).toFixed(1);

  // ── Geography globes ──
  const globes = getGeoGlobes(dino.geo);

  return `
    <div class="feedback-info">
      <div class="feedback-info-item full">
        <div class="fi-row"><span class="fi-main">${periodName}</span></div>
        <div class="fi-sub">${periodDates}</div>
        <div class="period-bar-wrap">
          <div class="period-bar">
            <div class="pt-t"></div><div class="pt-j"></div><div class="pt-c"></div>
          </div>
          <div class="period-marker" style="left:${markerPct}%"></div>
        </div>
        <div class="pt-labels"><span>Triassic</span><span>Jurassic</span><span>Cretaceous</span></div>
      </div>
      <div class="feedback-info-item">
        <div class="fi-label">Size</div>
        <div class="fi-main">${dino.length}m</div>
        <div class="fi-sub">${ft}ft</div>
        <div class="sizometer">${pips}<span class="sizo-label">${sizeLabel}</span></div>
      </div>
      <div class="feedback-info-item fi-centered">
        <div class="fi-main">${dino.diet}</div>
      </div>
      <div class="feedback-info-item full">
        <div class="fi-row"><span class="fi-emoji">📍</span><span class="fi-main">${dino.geo}</span><span class="fi-globes">${globes}</span></div>
      </div>
    </div>`;
}

function showAnswerView(correct, pts, q) {
  const area = document.getElementById('question-area');
  const infoDino = q.type === 'size-battle' ? q.bigger : q.correct;
  const correctName = q.type === 'size-battle' ? q.bigger.name : q.correct.name;

  const imgSrc = imageCache[infoDino.wiki];
  const imgHTML = imgSrc
    ? `<div class="answer-img-wrap">
        <img src="${imgSrc}" alt="${infoDino.name}" class="answer-dino-img"/>
        <button class="report-img-btn" onclick="reportImage('${infoDino.name.replace(/'/g,"\\'")}', '${imgSrc}', this)">⚑ Report image</button>
       </div>`
    : '';

  let factText = '';
  if (q.type !== 'size-battle') {
    const cached = factCache[q.correct.wiki] || { short: '', full: '' };
    if (cached.short) {
      const more = cached.full
        ? `<details class="answer-fact-more"><summary>Read more</summary><p>${cached.full}</p></details>`
        : '';
      factText = `<p class="answer-fact">${cached.short}</p>${more}`;
    }
  } else {
    const bigger = q.bigger;
    const smaller = bigger.name === q.a.name ? q.b : q.a;
    factText = `<p class="answer-fact">${bigger.name}: ${bigger.length}m &nbsp;·&nbsp; ${smaller.name}: ${smaller.length}m</p>`;
  }

  area.innerHTML = `
    <div class="answer-view ${correct ? 'correct' : 'wrong'}">
      <div class="answer-header">
        <span class="answer-icon">${correct ? '✅' : '❌'}</span>
        <span class="answer-label">${correct ? 'Correct!' : 'Nope!'}</span>
        ${correct
          ? `<span class="answer-pts">+${pts} pts</span>`
          : `<span class="answer-name">${correctName}</span>`}
      </div>
      ${imgHTML}
      ${factText}
      ${dinoInfoHTML(infoDino)}
      <div class="answer-tap-hint">tap or press space to continue</div>
    </div>`;
}

async function reportImage(dinoName, imgUrl, btnEl) {
  btnEl.disabled = true;
  btnEl.textContent = '✓ Reported';

  const report = { dino: dinoName, img: imgUrl, date: new Date().toISOString() };

  // Always save locally
  const stored = JSON.parse(localStorage.getItem('dinoquest_reports') || '[]');
  stored.push(report);
  localStorage.setItem('dinoquest_reports', JSON.stringify(stored));

  // Send to Discord webhook if configured
  const webhook = (typeof CONFIG !== 'undefined') && CONFIG.discordWebhook;
  if (webhook) {
    try {
      await fetch(webhook, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: `🚩 **Bad image report**\n**Dino:** ${dinoName}\n**Image:** ${imgUrl}`,
        }),
      });
    } catch { /* non-critical */ }
  }
}

function waitForAnswerDismiss() {
  return new Promise(resolve => {
    const area = document.getElementById('question-area');
    function onClick(e) {
      if (e.target.closest('.answer-fact-more')) return;
      area.removeEventListener('click', onClick);
      resolve();
    }
    // Delay so the click that triggered the answer doesn't immediately dismiss
    setTimeout(() => area.addEventListener('click', onClick), 0);
  });
}

function showHighScores(mode) {
  showScreen('screen-highscores');
  const scores = getTopScores(mode, 10);
  const tbody = document.getElementById('scores-table-body');
  tbody.innerHTML = '';
  if (scores.length === 0) {
    tbody.innerHTML = '<tr><td colspan="2" style="text-align:center">No scores yet!</td></tr>';
  } else {
    scores.forEach((s, i) => {
      const tr = document.createElement('tr');
      if (i === 0) tr.classList.add('gold');
      if (i === 1) tr.classList.add('silver');
      if (i === 2) tr.classList.add('bronze');
      tr.innerHTML = `<td>${i + 1}. ${s.initials}</td><td>${s.score}</td>`;
      tbody.appendChild(tr);
    });
  }
  document.getElementById('hs-mode-label').textContent = modeName(mode);
}

// ── Screens ───────────────────────────────────────────────────────────────────

function showScreen(id) {
  document.querySelectorAll('.screen').forEach(s => s.classList.remove('active'));
  document.getElementById(id).classList.add('active');
}

function setLoadingMessage(msg) {
  document.getElementById('loading-msg').textContent = msg;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function delay(ms) { return new Promise(r => setTimeout(r, ms)); }
function capitalize(s) { return s.charAt(0).toUpperCase() + s.slice(1); }
function modeName(m) {
  return { 'name-match': 'Name Match', 'pic-match': 'Picture Match', 'size-battle': 'Size Battle', 'dino-facts': 'Dino Facts' }[m] || m;
}

// ── Init ──────────────────────────────────────────────────────────────────────

document.addEventListener('keydown', e => {
  if (document.getElementById('screen-title').classList.contains('active')) {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      document.getElementById('btn-play').click();
    }
    return;
  }

  if (!document.getElementById('screen-game').classList.contains('active')) return;

  // Advance from answer view
  if (state.answeredThisRound) {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      document.getElementById('question-area').click();
    }
    return;
  }

  const buttons = getOptionButtons();
  if (!buttons.length) return;

  const dirMap = { ArrowRight: 'right', ArrowLeft: 'left', ArrowDown: 'down', ArrowUp: 'up' };
  const dir = dirMap[e.key];

  if (dir) {
    e.preventDefault();
    if (focusedOptionIndex === -1) {
      // Any arrow enters the grid at index 0; left/up jiggle the cursor
      if (dir === 'left' || dir === 'up') {
        jiggleKbCursor();
      } else {
        focusedOptionIndex = 0;
        applyKeyboardFocus(buttons);
      }
    } else {
      const next = gridMove(focusedOptionIndex, dir, buttons.length);
      if (next !== null) {
        focusedOptionIndex = next;
        applyKeyboardFocus(buttons);
      } else {
        jiggleFocused(buttons);
      }
    }
  } else if (e.key === ' ' || e.key === 'Enter') {
    e.preventDefault();
    if (focusedOptionIndex === -1) {
      jiggleKbCursor();
    } else if (focusedOptionIndex < buttons.length) {
      buttons[focusedOptionIndex].click();
    }
  }
});

document.addEventListener('DOMContentLoaded', () => {
  showScreen('screen-title');

  // Title screen
  document.getElementById('btn-play').addEventListener('click', () => startGame());
  document.getElementById('btn-scores-title').addEventListener('click', () => {
    showHighScores('dinoquest');
    document.getElementById('hs-back-btn').onclick = () => showScreen('screen-title');
  });

  // In-game
  document.getElementById('btn-quit-game').addEventListener('click', () => {
    if (confirm('Quit this game?')) showScreen('screen-title');
  });

  // Game over
  document.getElementById('btn-submit-score').addEventListener('click', submitScore);
  document.getElementById('btn-play-again').addEventListener('click', () => startGame());
  document.getElementById('btn-main-menu').addEventListener('click', () => showScreen('screen-title'));

  // Initials input: uppercase only, max 3
  const inp = document.getElementById('initials-input');
  inp.addEventListener('input', () => {
    inp.value = inp.value.toUpperCase().replace(/[^A-Z]/g, '').slice(0, 3);
  });
  inp.addEventListener('keydown', e => {
    if (e.key === 'Enter') submitScore();
  });

  // High scores back
  document.getElementById('hs-back-btn').addEventListener('click', () => showScreen('screen-title'));
});
