// Level data. Positions use 0-1 fractions of canvas size (400x700).
// Sizes (length, radius, size) are in absolute pixels at that canvas resolution.
// Auto-generated by admin.html — do not edit by hand.

// ── Global physics (apply to all levels) ────────────────────────────────────

const DEFAULT_GLOBALS = {
  "gravity": 0.095,
  "bounciness": 0.9
};

function getGlobals() {
  return { ...DEFAULT_GLOBALS };
}

// ── Level definitions ────────────────────────────────────────────────────────

const DEFAULT_LEVELS = [
  {
    "id": 1,
    "ballX": 0.5,
    "playerBar": {
      "x": 0.4815648854961834,
      "y": 0.6860341693929479,
      "rotation": -14,
      "length": 160
    },
    "items": [
      {
        "id": "bar-1",
        "type": "bar",
        "x": 0.28,
        "y": 0.31,
        "rotation": -38,
        "length": 130
      },
      {
        "id": "circle-1",
        "type": "circle",
        "x": 0.67,
        "y": 0.52,
        "radius": 26
      }
    ],
    "bucket": {
      "x": 0.8494147582697201,
      "y": 0.883413304252999,
      "width": 68,
      "height": 54,
      "wallThickness": 10,
      "rotation": 0
    }
  },
  {
    "id": 2,
    "ballX": 0.5,
    "playerBar": {
      "x": 0.37907124681933857,
      "y": 0.48757542711741164,
      "rotation": -121,
      "length": 160
    },
    "items": [
      {
        "id": "bar-1",
        "type": "bar",
        "x": 0.9154961832061069,
        "y": 0.045536168665939666,
        "rotation": -148,
        "length": 130
      },
      {
        "id": "circle-1",
        "type": "circle",
        "x": 0.6827226463104324,
        "y": 0.67848782260996,
        "radius": 26
      },
      {
        "id": "circle-1776035117362",
        "type": "circle",
        "x": 0.42548982188295165,
        "y": 0.6755252635405308,
        "radius": 40
      },
      {
        "id": "circle-1776035125245",
        "type": "circle",
        "x": 0.6297709923664122,
        "y": 0.7984005816066885,
        "radius": 28
      }
    ],
    "bucket": {
      "x": 0.8494147582697201,
      "y": 0.883413304252999,
      "width": 68,
      "height": 54,
      "wallThickness": 10,
      "rotation": 0
    }
  },
  {
    "id": 3,
    "ballX": 0.5,
    "playerBar": {
      "x": 0.5940712468193386,
      "y": 0.6575754271174117,
      "rotation": -99,
      "length": 160
    },
    "items": [
      {
        "id": "bar-1",
        "type": "bar",
        "x": 0.4479961832061069,
        "y": 0.15839331152308245,
        "rotation": -93,
        "length": 130
      },
      {
        "id": "circle-1",
        "type": "circle",
        "x": 0.5552226463104324,
        "y": 0.9713449654671029,
        "radius": 26
      },
      {
        "id": "circle-1776035117362",
        "type": "circle",
        "x": 0.30798982188295165,
        "y": 0.7383824063976736,
        "radius": 55
      },
      {
        "id": "circle-1776035125245",
        "type": "circle",
        "x": 0.2622709923664122,
        "y": 0.9669720101781172,
        "radius": 28
      },
      {
        "id": "bar-1776040422154",
        "type": "bar",
        "x": 0.745,
        "y": 0.31857142857142856,
        "rotation": -91,
        "length": 130
      },
      {
        "id": "bar-1776040476119",
        "type": "bar",
        "x": 0.5,
        "y": 0.4,
        "rotation": 72,
        "length": 130
      },
      {
        "id": "bar-1776040480637",
        "type": "bar",
        "x": 0.85,
        "y": 0.67,
        "rotation": 87,
        "length": 130
      }
    ],
    "bucket": {
      "x": 0.10941475826972008,
      "y": 0.8319847328244275,
      "width": 68,
      "height": 54,
      "wallThickness": 10,
      "rotation": 90
    }
  }
];

function getLevels() {
  return JSON.parse(JSON.stringify(DEFAULT_LEVELS));
}

function getLevel(id) {
  return getLevels().find(l => l.id === id) || getLevels()[0];
}

// saveLevels / saveGlobals are no-ops — persistence goes through the server.
function saveLevels() {}
function saveGlobals() {}
