// Level data. Positions use 0-1 fractions of canvas size (400x700).
// Sizes (length, radius, size) are in absolute pixels at that canvas resolution.
// Auto-generated by admin.html — do not edit by hand.

// ── Global physics (apply to all levels) ────────────────────────────────────

const DEFAULT_GLOBALS = {
  "gravity": 0.095,
  "bounciness": 0.9
};

function getGlobals() {
  return { ...DEFAULT_GLOBALS };
}

// ── Level definitions ────────────────────────────────────────────────────────

const DEFAULT_LEVELS = [
  {
    "id": 1,
    "ballX": 0.5,
    "playerBar": {
      "x": 0.44656488549618345,
      "y": 0.703177026535805,
      "rotation": -10,
      "length": 160
    },
    "items": [
      {
        "id": "bar-1",
        "type": "bar",
        "x": 0.28,
        "y": 0.31,
        "rotation": -38,
        "length": 130
      },
      {
        "id": "circle-1",
        "type": "circle",
        "x": 0.67,
        "y": 0.52,
        "radius": 26
      }
    ],
    "bucket": {
      "x": 0.8494147582697201,
      "y": 0.883413304252999,
      "width": 68,
      "height": 54,
      "wallThickness": 10,
      "rotation": 0
    }
  }
];

function getLevels() {
  return JSON.parse(JSON.stringify(DEFAULT_LEVELS));
}

function getLevel(id) {
  return getLevels().find(l => l.id === id) || getLevels()[0];
}

// saveLevels / saveGlobals are no-ops — persistence goes through the server.
function saveLevels() {}
function saveGlobals() {}
