// Level data. Positions use 0-1 fractions of canvas size (400x700).
// Sizes (length, radius, size) are in absolute pixels at that canvas resolution.
// Auto-generated by admin.html — do not edit by hand.

// ── Global physics (apply to all levels) ────────────────────────────────────

const DEFAULT_GLOBALS = {
  "gravity": 0.095,
  "bounciness": 0.9
};

function getGlobals() {
  return { ...DEFAULT_GLOBALS };
}

// ── Level definitions ────────────────────────────────────────────────────────

const DEFAULT_LEVELS = [
  {
    "id": 1,
    "ballX": 0.5,
    "playerBar": {
      "x": 0.4815648854961834,
      "y": 0.6860341693929479,
      "rotation": -14,
      "length": 160
    },
    "items": [
      {
        "id": "bar-1",
        "type": "bar",
        "x": 0.28,
        "y": 0.31,
        "rotation": -38,
        "length": 130
      },
      {
        "id": "circle-1",
        "type": "circle",
        "x": 0.67,
        "y": 0.52,
        "radius": 26
      }
    ],
    "bucket": {
      "x": 0.8494147582697201,
      "y": 0.883413304252999,
      "width": 68,
      "height": 54,
      "wallThickness": 10,
      "rotation": 0
    }
  },
  {
    "id": 2,
    "ballX": 0.5,
    "playerBar": {
      "x": 0.30407124681933867,
      "y": 0.4647182842602688,
      "rotation": -135,
      "length": 160
    },
    "items": [
      {
        "id": "bar-1",
        "type": "bar",
        "x": 0.1654961832061069,
        "y": 0.299821882951654,
        "rotation": -141,
        "length": 130
      },
      {
        "id": "circle-1",
        "type": "circle",
        "x": 0.6827226463104324,
        "y": 0.67848782260996,
        "radius": 26
      },
      {
        "id": "circle-1776035117362",
        "type": "circle",
        "x": 0.5279898218829516,
        "y": 0.6340966921119593,
        "radius": 28
      },
      {
        "id": "circle-1776035125245",
        "type": "circle",
        "x": 0.6297709923664122,
        "y": 0.7984005816066885,
        "radius": 28
      }
    ],
    "bucket": {
      "x": 0.8494147582697201,
      "y": 0.883413304252999,
      "width": 68,
      "height": 54,
      "wallThickness": 10,
      "rotation": 0
    }
  }
];

function getLevels() {
  return JSON.parse(JSON.stringify(DEFAULT_LEVELS));
}

function getLevel(id) {
  return getLevels().find(l => l.id === id) || getLevels()[0];
}

// saveLevels / saveGlobals are no-ops — persistence goes through the server.
function saveLevels() {}
function saveGlobals() {}
