// ── Bundled data (from animal-data.js, generated by make fetch-animal-data) ────
// Pre-populate caches so no Wikipedia API calls are needed at runtime.
const imageCache = {};
const factCache = {};

if (typeof ANIMAL_DATA !== 'undefined') {
  for (const [wiki, data] of Object.entries(ANIMAL_DATA)) {
    if (data.img)   imageCache[wiki] = data.img;
    if (data.short) factCache[wiki]  = { short: data.short, full: data.full || '' };
  }
}

// ── No live Wikipedia fetching — all data must come from animal-data.js ────────

// ── Keyboard navigation ───────────────────────────────────────────────────────
let focusedOptionIndex = -1;

function getOptionButtons() {
  return Array.from(document.querySelectorAll('#question-area [data-name]'));
}

function applyKeyboardFocus(buttons) {
  buttons.forEach((btn, i) => {
    btn.classList.toggle('keyboard-focus', i === focusedOptionIndex);
  });
  if (focusedOptionIndex === -1) {
    showKbCursor();
  } else {
    hideKbCursor();
  }
}

function resetKeyboardFocus() {
  focusedOptionIndex = -1;
  applyKeyboardFocus(getOptionButtons());
}

function showKbCursor() {
  document.querySelectorAll('.kb-cursor').forEach(el => el.remove());
  const firstBtn = getOptionButtons()[0];
  if (!firstBtn) return;
  const container = firstBtn.parentElement;
  container.style.position = 'relative';
  const cursor = document.createElement('div');
  cursor.className = 'kb-cursor';
  cursor.textContent = '▶';
  container.appendChild(cursor);
}

function hideKbCursor() {
  document.querySelectorAll('.kb-cursor').forEach(el => el.remove());
}

function jiggleKbCursor() {
  const cursor = document.querySelector('#question-area .kb-cursor');
  if (!cursor) return;
  cursor.classList.add('keyboard-jiggle');
  cursor.addEventListener('animationend', () => cursor.classList.remove('keyboard-jiggle'), { once: true });
}

// battle-type questions use 1 column (vertical stack); other layouts use 2 columns
function getGridCols() {
  const t = state.currentQ && state.currentQ.type;
  return t === 'faster' ? 1 : 2;
}

function gridMove(index, direction, total) {
  const cols = getGridCols();
  const col = index % cols;
  const row = Math.floor(index / cols);
  const maxRow = Math.floor((total - 1) / cols);

  if (direction === 'right' && col < cols - 1 && index + 1 < total) return index + 1;
  if (direction === 'left'  && col > 0)                              return index - 1;
  if (direction === 'down'  && row < maxRow && index + cols < total) return index + cols;
  if (direction === 'up'    && row > 0)                              return index - cols;
  return null;
}

function jiggleFocused(buttons) {
  const btn = buttons[focusedOptionIndex];
  if (!btn) return;
  btn.classList.add('keyboard-jiggle');
  btn.addEventListener('animationend', () => btn.classList.remove('keyboard-jiggle'), { once: true });
}

// ── Session persistence ───────────────────────────────────────────────────────
const SESSION_KEY = 'cenozoiquest_session';

function saveSession() {
  const data = {
    level: state.level,
    score: state.score,
    lives: state.lives,
    streak: state.streak,
    perfectStreak: state.perfectStreak,
    usedCorrects: [...state.usedCorrects],
  };
  localStorage.setItem(SESSION_KEY, JSON.stringify(data));
}

function loadSession() {
  try {
    const raw = localStorage.getItem(SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch { return null; }
}

function clearSession() {
  localStorage.removeItem(SESSION_KEY);
}

// ── Game state ────────────────────────────────────────────────────────────────
let state = {
  score: 0,
  streak: 0,
  questionNum: 0,
  totalQuestions: 5,
  level: 1,
  lives: 3,
  devMode: false,
  perfectStreak: 0,  // consecutive perfect levels
  pool: [],
  imageAnimals: [],
  currentQ: null,
  answeredThisRound: false,
  usedCorrects: new Set(),
  results: [],
  noImages: false,
};

const SCORE_MULT = 1.5;

// Each question gets its mode from this rotating sequence
const ALL_MODES = [
  'name-match', 'faster', 'pic-match',
];
// Fallback when no images are available (no animal-data.js yet)
const MODE_SEQUENCE_NO_IMAGES = [
  'faster', 'faster', 'faster', 'faster', 'faster',
];

function buildPool() {
  return [...ANIMALS];
}

function pick(arr, n) {
  const copy = [...arr];
  const result = [];
  while (result.length < n && copy.length) {
    const i = Math.floor(Math.random() * copy.length);
    result.push(copy.splice(i, 1)[0]);
  }
  return result;
}

function calcPoints(correct) {
  if (!correct) return 0;
  const base = 100;
  const streakBonus = Math.min(state.streak * 10, 50);
  return Math.round((base + streakBonus) * SCORE_MULT);
}

// ── Question builders ─────────────────────────────────────────────────────────

// Map game level → max animal difficulty level shown as correct answer
function maxAnimalLevel() {
  const g = state.level;
  if (g <=  5) return 2;
  if (g <= 10) return 3;
  if (g <= 15) return 4;
  return 5;
}

function pickFreshCorrect() {
  const unused = state.pool.filter(d => !state.usedCorrects.has(d.name));
  const inRange = unused.filter(d => d.level <= maxAnimalLevel());
  const candidates = inRange.length >= 1 ? inRange : unused;
  if (candidates.length === 0 && !state.devMode) {
    notifyLoopAround();
  }
  const [correct] = pick(candidates.length >= 1 ? candidates : state.pool, 1);
  state.usedCorrects.add(correct.name);
  return correct;
}

function notifyLoopAround() {
  const webhook = (typeof CONFIG !== 'undefined') && CONFIG.discordWebhook;
  if (!webhook) return;
  const msg = `🔁 A player looped around! Level ${state.level}, score ${state.score} — they've seen all the animals.`;
  fetch(webhook, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ content: msg }),
  }).catch(() => {});
}

function buildNameMatchQuestion() {
  const imgPool = state.imageAnimals;
  const correct = pick(imgPool.filter(d => !state.usedCorrects.has(d.name)), 1)[0]
    || pick(imgPool, 1)[0];
  state.usedCorrects.add(correct.name);
  const wrongs = pick(imgPool.filter(d => d.name !== correct.name), 3);
  const options = pick([correct, ...wrongs], 4); // shuffled
  return { type: 'name-match', correct, options, imgSrc: imageCache[correct.wiki] };
}

function buildPicMatchQuestion() {
  const imgPool = state.imageAnimals;
  const correct = pick(imgPool.filter(d => !state.usedCorrects.has(d.name)), 1)[0]
    || pick(imgPool, 1)[0];
  state.usedCorrects.add(correct.name);
  const wrongs = pick(imgPool.filter(d => d.name !== correct.name), 3);
  const options = pick([correct, ...wrongs], 4);
  return { type: 'pic-match', correct, options };
}

function buildEvolvedFirstQuestion() {
  const unused  = state.pool.filter(d => !state.usedCorrects.has(d.name));
  const inRange = unused.filter(d => d.level <= maxAnimalLevel());
  const sourcePool = inRange.length >= 2 ? inRange : (unused.length >= 2 ? unused : state.pool);

  let a, b, attempts = 0;
  do {
    [a, b] = pick(sourcePool, 2);
    attempts++;
  } while (Math.abs(a.appeared - b.appeared) < 0.5 && attempts < 30);

  // Enforce modern-vs-extinct rule: living animals (appeared ≤ 0.001) are always newer
  const earlier = a.appeared > b.appeared ? a : b;

  state.usedCorrects.add(a.name);
  state.usedCorrects.add(b.name);
  return { type: 'evolved-first', a, b, earlier };
}

function buildFasterQuestion() {
  const unused  = state.pool.filter(d => !state.usedCorrects.has(d.name));
  const inRange = unused.filter(d => d.level <= maxAnimalLevel());
  const sourcePool = inRange.length >= 2 ? inRange : (unused.length >= 2 ? unused : state.pool);

  let a, b, attempts = 0;
  do {
    [a, b] = pick(sourcePool, 2);
    attempts++;
  } while (Math.abs(a.speed - b.speed) < 2 && attempts < 30);

  const faster = a.speed > b.speed ? a : b;

  state.usedCorrects.add(a.name);
  state.usedCorrects.add(b.name);
  return { type: 'faster', a, b, faster };
}

async function nextQuestion() {
  state.answeredThisRound = false;
  state.questionNum++;
  state.results[state.questionNum - 1] = 'current';
  updateProgressTrack();

  const modeList = state.noImages ? MODE_SEQUENCE_NO_IMAGES : ALL_MODES;
  const mode = modeList[((state.level - 1) + (state.questionNum - 1)) % modeList.length];
  let q;
  switch (mode) {
    case 'name-match':    q = buildNameMatchQuestion();    break;
    case 'pic-match':     q = buildPicMatchQuestion();     break;
    case 'faster':        q = buildFasterQuestion();       break;
  }
  state.currentQ = q;
  await renderQuestion(q);
}

// ── Game flow ─────────────────────────────────────────────────────────────────

async function startGame() {
  const qp = new URLSearchParams(window.location.search);
  state.devMode = qp.get('dev') === '1';
  state.score = 0;
  state.streak = 0;
  state.level = Math.max(1, parseInt(qp.get('level') ?? '1', 10) || 1);
  state.lives = state.devMode ? 99 : Math.max(1, parseInt(qp.get('lives') ?? '3', 10) || 3);
  state.perfectStreak = 0;
  state.questionNum = 0;
  state.pool = buildPool();
  state.usedCorrects = new Set();

  const imageAnimals = state.pool.filter(d => imageCache[d.wiki]);
  if (imageAnimals.length < 4) {
    showScreen('screen-loading');
    setLoadingMessage('⚠️ Run "make fetch-animal-data" to load animal images & facts.');
    return;
  }
  state.imageAnimals = imageAnimals;
  state.noImages = false;

  state.results = Array(state.totalQuestions).fill('pending');
  showScreen('screen-game');
  updateHUD();
  updateProgressTrack();
  await nextQuestion();
}

async function resumeGame() {
  const session = loadSession();
  if (!session) { startGame(); return; }

  const qp = new URLSearchParams(window.location.search);
  state.devMode     = qp.get('dev') === '1';
  state.level       = session.level;
  state.score       = session.score;
  state.lives       = session.lives;
  state.streak      = session.streak;
  state.perfectStreak = session.perfectStreak;
  state.questionNum = 0;
  state.pool        = buildPool();
  state.usedCorrects = new Set(session.usedCorrects || []);
  state.results     = Array(state.totalQuestions).fill('pending');
  state.answeredThisRound = false;

  const imageAnimals = state.pool.filter(d => imageCache[d.wiki]);
  state.imageAnimals = imageAnimals;
  state.noImages   = false;

  // Show map for current level (level-1 was just completed)
  await showMapScreen(state.level - 1);

  showScreen('screen-game');
  updateHUD();
  updateProgressTrack();
  await nextQuestion();
}

async function endLevel() {
  const justCompleted = state.level;
  const wasPerfect = state.results.every(r => r === 'correct');

  if (wasPerfect) {
    state.perfectStreak++;
    if (state.perfectStreak >= 3) {
      state.perfectStreak = 0;
      state.lives++;
      await awardExtraLife();
    }
  } else {
    state.perfectStreak = 0;
  }

  state.level++;
  state.questionNum = 0;
  state.results = Array(state.totalQuestions).fill('pending');
  state.answeredThisRound = false;

  await showMapScreen(justCompleted);

  showScreen('screen-game');
  updateHUD();
  updateProgressTrack();
  await nextQuestion();
}

// ── Map screen ────────────────────────────────────────────────────────────────

const LEVELS_PER_WORLD = 5;

// 5 nodes evenly spaced on a single horizontal row
const MAP_NODE_POS = [
  { x: 12, y: 50 },
  { x: 31, y: 50 },
  { x: 50, y: 50 },
  { x: 69, y: 50 },
  { x: 88, y: 50 },
];

const WORLD_THEMES = [
  { label: 'Dust Bowl',   accent: '#d4915a', done: '#8d5a2a', line: '#e8b98a', bg: '#1a1008', border: '#4a2e12', glow: '#120a04' },
  { label: 'River',       accent: '#4fc3f7', done: '#0277bd', line: '#a8d8f0', bg: '#020e18', border: '#08304a', glow: '#010912' },
  { label: 'Glades',      accent: '#81c784', done: '#2e7d32', line: '#c8e6c9', bg: '#081408', border: '#1a3a1a', glow: '#040d04' },
  { label: 'White Sand',  accent: '#f5e6c8', done: '#b8a070', line: '#fffde7', bg: '#1a1810', border: '#4a4430', glow: '#120f08' },
  { label: 'Tundra',      accent: '#b3d9e8', done: '#4a90b8', line: '#e8f4f8', bg: '#080e14', border: '#1a3040', glow: '#04080d' },
  { label: 'Neptune',     accent: '#3f51b5', done: '#1a237e', line: '#9fa8da', bg: '#04051a', border: '#10144a', glow: '#020310' },
  { label: 'Black Hole',  accent: '#ce93d8', done: '#6a1b9a', line: '#f3e5f5', bg: '#020004', border: '#1a0820', glow: '#010002' },
  { label: 'X7 Star',     accent: '#fff176', done: '#c8a800', line: '#fffff0', bg: '#1a1800', border: '#4a4400', glow: '#100f00' },
  { label: 'School Yard', accent: '#aed581', done: '#558b2f', line: '#dcedc8', bg: '#0d1408', border: '#283a10', glow: '#080d04' },
  { label: 'X-Pluto',     accent: '#80cbc4', done: '#00695c', line: '#e0f2f1', bg: '#020e0c', border: '#0a2e28', glow: '#010908' },
];

function getPosForLevel(level) {
  return MAP_NODE_POS[(level - 1) % LEVELS_PER_WORLD];
}

function renderMapCanvas(worldStart, completedLevel, theme) {
  const canvas = document.getElementById('map-canvas');
  canvas.querySelectorAll('.map-node, .map-svg').forEach(el => el.remove());

  // Apply world theme
  canvas.style.background   = theme.bg;
  canvas.style.borderColor  = theme.border;

  // SVG lines — preserveAspectRatio:none so % coords match CSS exactly
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.setAttribute('class', 'map-svg');
  svg.setAttribute('viewBox', '0 0 100 100');
  svg.setAttribute('preserveAspectRatio', 'none');

  for (let i = 0; i < MAP_NODE_POS.length - 1; i++) {
    const a = MAP_NODE_POS[i];
    const b = MAP_NODE_POS[i + 1];
    if (worldStart + i >= completedLevel) continue; // only already-completed segments
    const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
    line.setAttribute('x1', a.x); line.setAttribute('y1', a.y);
    line.setAttribute('x2', b.x); line.setAttribute('y2', b.y);
    line.setAttribute('stroke', theme.line);
    line.setAttribute('stroke-width', '3');
    line.setAttribute('stroke-linecap', 'round');
    svg.appendChild(line);
  }
  canvas.insertBefore(svg, canvas.firstChild);

  // Nodes
  for (let i = 0; i < MAP_NODE_POS.length; i++) {
    const lvl = worldStart + i;
    const pos = MAP_NODE_POS[i];
    const node = document.createElement('div');
    node.className = 'map-node';
    if (lvl <= completedLevel) {
      node.classList.add('done');
      node.textContent = '✓';
      node.style.background   = theme.done;
      node.style.borderColor  = theme.line;
    } else if (lvl === completedLevel + 1) {
      node.classList.add('next');
      node.textContent = lvl;
    } else {
      node.classList.add('future');
      node.textContent = lvl;
    }
    node.style.left = pos.x + '%';
    node.style.top  = pos.y + '%';
    canvas.appendChild(node);
  }
}

function showMapScreen(justCompleted) {
  saveSession();
  return new Promise(resolve => {
    showScreen('screen-map');

    const nextLevel  = justCompleted + 1;
    const worldIdx   = Math.floor((nextLevel - 1) / LEVELS_PER_WORLD);
    const worldStart = worldIdx * LEVELS_PER_WORLD + 1;
    const theme      = WORLD_THEMES[worldIdx % WORLD_THEMES.length];
    const isNewWorld = justCompleted % LEVELS_PER_WORLD === 0;
    state.theme = theme;

    document.getElementById('screen-map').style.background = '#0d0d0d';

    const worldLabel = document.getElementById('map-world-label');
    worldLabel.textContent = theme.label;
    worldLabel.style.color = theme.accent;

    document.getElementById('map-level-label').textContent   = `Level ${nextLevel}`;
    document.getElementById('map-score-display').textContent = `Score: ${state.score}`;
    document.getElementById('map-lives-display').textContent = state.devMode ? '🦣 ∞' : '🦣'.repeat(Math.max(0, state.lives));

    // completedLevel relative to this world: 0 if entering fresh, otherwise the last done node
    const completedInWorld = isNewWorld ? worldStart - 1 : justCompleted;
    renderMapCanvas(worldStart, completedInWorld, theme);

    // Dino animation
    const dinoEl = document.getElementById('map-dino');
    const to     = getPosForLevel(nextLevel);

    if (isNewWorld) {
      // World transition overlay
      const announce     = document.getElementById('world-announce');
      const announceNum  = document.getElementById('world-announce-num');
      const announceName = document.getElementById('world-announce-name');
      announceNum.textContent  = `World ${worldIdx + 1}`;
      announceName.textContent = theme.label;
      announceName.style.color = theme.accent;
      announce.classList.remove('active');
      void announce.offsetWidth; // force reflow to restart animation
      announce.classList.add('active');
      setTimeout(() => announce.classList.remove('active'), 2600);

      // Enter dino from off-screen left, delayed until after overlay peaks
      dinoEl.style.transition = 'none';
      dinoEl.style.left = '-8%';
      dinoEl.style.top  = to.y + '%';
      setTimeout(() => {
        dinoEl.style.transition = 'left 0.7s cubic-bezier(.4,0,.2,1)';
        dinoEl.style.left = to.x + '%';
      }, 1400);
    } else {
      const from = getPosForLevel(justCompleted);
      dinoEl.style.transition = 'none';
      dinoEl.style.left = from.x + '%';
      dinoEl.style.top  = from.y + '%';
      setTimeout(() => {
        // Move dino and draw line simultaneously
        dinoEl.style.transition = 'left 0.7s cubic-bezier(.4,0,.2,1), top 0.7s cubic-bezier(.4,0,.2,1)';
        dinoEl.style.left = to.x + '%';
        dinoEl.style.top  = to.y + '%';

        const svg = document.querySelector('#map-canvas .map-svg');
        if (svg) {
          const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
          line.setAttribute('x1', from.x); line.setAttribute('y1', from.y);
          line.setAttribute('x2', to.x);   line.setAttribute('y2', to.y);
          line.setAttribute('stroke', theme.line);
          line.setAttribute('stroke-width', '3');
          line.setAttribute('stroke-linecap', 'round');
          svg.appendChild(line);
        }
      }, 500);
    }

    // Show continue button after animation
    const btn = document.getElementById('btn-map-continue');
    btn.style.opacity = '0';
    btn.style.pointerEvents = 'none';
    const onContinue = () => {
      btn.removeEventListener('click', onContinue);
      resolve();
    };
    btn.addEventListener('click', onContinue);
    setTimeout(() => {
      btn.style.transition = 'opacity 0.3s';
      btn.style.opacity = '1';
      btn.style.pointerEvents = '';
    }, isNewWorld ? 2800 : 1400);
  });
}

async function handleAnswer(chosen) {
  if (state.answeredThisRound) return;
  state.answeredThisRound = true;

  const q = state.currentQ;
  let correct = false;

  if (q.type === 'name-match' || q.type === 'pic-match') {
    correct = chosen.name === q.correct.name;
  } else if (q.type === 'faster') {
    correct = chosen.name === q.faster.name;
  }

  if (correct) {
    state.streak++;
    const pts = calcPoints(true);
    state.score += pts;
    state.results[state.questionNum - 1] = 'correct';
    showAnswerView(true, pts, q);
  } else {
    state.streak = 0;
    state.lives--;
    state.results[state.questionNum - 1] = 'wrong';
    saveSession();
    showAnswerView(false, 0, q);
  }

  updateHUD();
  updateProgressTrack();

  if (correct && state.results.every(r => r === 'correct')) {
    setTimeout(celebratePerfectLevel, 120);
  }

  await waitForAnswerDismiss();

  if (state.lives <= 0 && !state.devMode) {
    endGame();
  } else if (state.questionNum >= state.totalQuestions) {
    await endLevel();
  } else {
    await nextQuestion();
  }
}

function celebratePerfectLevel() {
  const track = document.getElementById('progress-track');
  const boxes = document.getElementById('progress-boxes');
  if (!track || !boxes) return;

  // Flash each box bright gold, cascading top→bottom (boxes render reversed, so index 0 = top = last question)
  const boxEls = Array.from(boxes.querySelectorAll('.progress-box'));
  boxEls.forEach((box, i) => {
    setTimeout(() => {
      box.classList.add('perfect-flash');
      setTimeout(() => box.classList.remove('perfect-flash'), 500);
    }, i * 80);
  });

  // Spawn sparkle particles down the right edge of the box stack
  const CHARS = ['⭐', '✨', '🌟', '⭐', '✨', '🌟', '⭐', '✨', '🌟', '⭐'];
  const totalH = boxes.offsetHeight;
  const offsetTop = boxes.offsetTop;
  CHARS.forEach((ch, i) => {
    setTimeout(() => {
      const el = document.createElement('div');
      el.className = 'perfect-particle';
      el.textContent = ch;
      el.style.top = (offsetTop + (i / CHARS.length) * totalH) + 'px';
      track.appendChild(el);
      el.addEventListener('animationend', () => el.remove());
    }, i * 60);
  });
}

function awardExtraLife() {
  return new Promise(resolve => {
    const overlay = document.createElement('div');
    overlay.className = 'extra-life-overlay';
    overlay.innerHTML = `
      <div class="el-dinos" aria-hidden="true">
        <span class="el-dino el-dino-l">🦣</span>
        <span class="el-dino el-dino-r">🦣</span>
      </div>
      <div class="el-streak">🔥 3 Perfect Levels! 🔥</div>
      <div class="el-main">+1 🦣</div>
      <div class="el-sub">Extra Life!</div>
      <div class="el-sparks" aria-hidden="true">
        ${Array.from({length: 12}, (_, i) => `<span class="el-spark" style="--i:${i}"></span>`).join('')}
      </div>
    `;
    document.body.appendChild(overlay);

    // Flash the lives display too
    const livesEl = document.getElementById('hud-lives');
    livesEl.classList.add('lives-bonus');
    livesEl.addEventListener('animationend', () => livesEl.classList.remove('lives-bonus'), { once: true });

    setTimeout(() => {
      overlay.classList.add('el-out');
      overlay.addEventListener('animationend', () => { overlay.remove(); resolve(); }, { once: true });
    }, 2400);
  });
}

function endGame() {
  clearSession();
  showScreen('screen-gameover');
  document.getElementById('final-score').textContent = state.score;
  document.getElementById('final-mode').textContent = `After Impact · Level ${state.level}`;

  const best = getLocalBest();
  const isHigh = state.score > best;
  document.getElementById('highscore-msg').textContent = isHigh
    ? '🏆 New High Score!'
    : `Your Best: ${best}`;

  document.getElementById('initials-input').value = '';
  document.getElementById('initials-error').textContent = '';
}

async function submitScore() {
  const raw = document.getElementById('initials-input').value.toUpperCase().trim();
  if (!isValidInitials(raw)) {
    document.getElementById('initials-error').textContent =
      raw.length !== 3 ? 'Enter exactly 3 letters.' : 'Choose different initials!';
    return;
  }
  const btn = document.getElementById('btn-submit-score');
  btn.disabled = true;
  await saveScore({ initials: raw, score: state.score });
  btn.disabled = false;
  showHighScores();
}

// ── Render ────────────────────────────────────────────────────────────────────

function updateProgressTrack() {
  const boxes = document.getElementById('progress-boxes');
  if (!boxes) return;
  boxes.innerHTML = '';
  // Render reversed so question 1 is at the bottom, 10 at the top
  for (let i = state.totalQuestions - 1; i >= 0; i--) {
    const box = document.createElement('div');
    box.className = 'progress-box ' + (state.results[i] || 'pending');
    boxes.appendChild(box);
  }
}

function updateHUD() {
  document.getElementById('hud-score').textContent = state.score;
  document.getElementById('hud-streak').textContent = state.streak >= 2 ? `🔥 x${state.streak}` : '';
  document.getElementById('hud-lives').textContent  = state.devMode ? '🦣 ∞' : '🦣'.repeat(Math.max(0, state.lives));
  document.getElementById('hud-level-num').textContent = state.level;

  const worldIdx = Math.floor((state.level - 1) / LEVELS_PER_WORLD);
  const theme = WORLD_THEMES[worldIdx % WORLD_THEMES.length];
  const worldEl = document.getElementById('hud-world-label');
  worldEl.textContent = theme.label;
  worldEl.style.color = theme.accent;

  // Perfect streak pips — 3 circles, filled up to perfectStreak count
  const pips = document.querySelectorAll('#hud-perfect-streak .streak-pip');
  pips.forEach((pip, i) => pip.classList.toggle('lit', i < state.perfectStreak));
}

function animalCard(animal) {
  const img = imageCache[animal.wiki];
  return `
    <button class="size-card" data-name="${animal.name}">
      ${img ? `<img src="${img}" alt="${animal.name}"/>` : '<div class="no-img">?</div>'}
      <span class="size-name">${animal.name}${animal.extinct ? ' 💀' : ''}</span>
    </button>`;
}

async function renderQuestion(q) {
  const area = document.getElementById('question-area');
  area.innerHTML = '';

  if (q.type === 'name-match') {
    area.innerHTML = `
      <p class="question-prompt">Which animal is this?</p>
      <div class="dino-image-wrap">
        <img src="${q.imgSrc}" alt="mystery animal" class="dino-img" onerror="this.style.display='none'"/>
      </div>
      <div class="options grid-2">
        ${q.options.map(d => `<button class="option-btn" data-name="${d.name}">${d.name}</button>`).join('')}
      </div>`;
  } else if (q.type === 'pic-match') {
    area.innerHTML = `
      <p class="question-prompt">Find the picture of: <strong>${q.correct.name}</strong></p>
      <div class="options grid-2 pic-grid">
        ${q.options.map(d => {
          const src = imageCache[d.wiki] || '';
          return `<button class="option-btn pic-btn" data-name="${d.name}">
            <img src="${src}" alt="${d.name}" onerror="this.style.display='none'"/>
            </button>`;
        }).join('')}
      </div>`;
  } else if (q.type === 'faster') {
    area.innerHTML = `
      <p class="question-prompt">Which is <strong>FASTER</strong>?</p>
      <div class="size-battle-wrap">
        ${animalCard(q.a)}
        <div class="vs-badge">VS</div>
        ${animalCard(q.b)}
      </div>`;
  }

  // Wire up button clicks
  area.querySelectorAll('[data-name]').forEach(btn => {
    btn.addEventListener('click', () => {
      const animal = ANIMALS.find(x => x.name === btn.dataset.name);
      if (animal) handleAnswer(animal);
    });
  });

  resetKeyboardFocus();

  const hint = document.querySelector('.kb-hint');
  if (hint) {
    const isBattle = q.type === 'evolved-first' || q.type === 'faster';
    hint.innerHTML = isBattle
      ? '↑ ↓ navigate &nbsp;·&nbsp; Space to select'
      : '← → navigate &nbsp;·&nbsp; Space to select';
  }
}

function getSizeLevel(m) {
  if (m <  1)  return { level: 1, label: 'Tiny' };
  if (m <  4)  return { level: 2, label: 'Small' };
  if (m < 10)  return { level: 3, label: 'Medium' };
  if (m < 20)  return { level: 4, label: 'Large' };
  return              { level: 5, label: 'Enormous' };
}

function parseMidMa(period) {
  const m = period.match(/\(~?(\d+)(?:[–\-](\d+))?\s*Ma\)/);
  if (!m) return null;
  const a = parseInt(m[1]), b = m[2] ? parseInt(m[2]) : a;
  return (a + b) / 2;
}

function getGeoGlobes(geo) {
  const g = geo.toLowerCase();
  const out = new Set();
  if (g.includes('north america') || g.includes('south america')) out.add('🌎');
  if (g.includes('europe') || g.includes('africa'))               out.add('🌍');
  if (g.includes('asia'))                                          out.add('🌏');
  if (g.includes('ocean') || g.includes('worldwide'))             out.add('🌊');
  return [...out].join(' ');
}

function sizeComparisonHTML(lengthM) {
  const humanM = 1.8;
  const maxM = Math.max(lengthM, humanM);
  const humanPct = (humanM / maxM * 100).toFixed(1);
  const dinoPct  = (lengthM  / maxM * 100).toFixed(1);
  return `
    <div class="size-comp">
      <div class="fi-label">vs Human</div>
      <div class="sc-row">
        <span class="sc-emoji">🧍</span>
        <div class="sc-bar-wrap"><div class="sc-bar sc-human" style="width:${humanPct}%"></div></div>
        <span class="sc-val">1.8m</span>
      </div>
      <div class="sc-row">
        <span class="sc-emoji">🦣</span>
        <div class="sc-bar-wrap"><div class="sc-bar sc-dino" style="width:${dinoPct}%"></div></div>
        <span class="sc-val">${lengthM}m</span>
      </div>
    </div>`;
}

function parseEndMa(animal) {
  if (!animal.extinct) return 0;
  const m = animal.period.match(/[–\-]([\d.]+)\s*Ma/);
  return m ? parseFloat(m[1]) : 0;
}

function animalInfoHTML(animal) {
  const ft = (animal.length * 3.281).toFixed(1);
  const mph = Math.round(animal.speed * 0.621);
  const { level, label: sizeLabel } = getSizeLevel(animal.length);
  const pips = Array.from({ length: 5 }, (_, i) =>
    `<span class="sizo-pip ${i < level ? 'on' : 'off'}"></span>`
  ).join('');
  const globes = getGeoGlobes(animal.geo);
  const extinctBadge = animal.extinct
    ? '<span class="extinct-badge">💀 Extinct</span>'
    : '<span class="extant-badge">🌿 Still alive today!</span>';

  // ── Lifespan bar (66 Ma = K-Pg impact, left; 0 Ma = today, right) ──
  const TOTAL_MA = 66;
  const ERAS = [
    { abbr: 'Paleogene',  start: 66,  end: 23,  color: '#8B6844' },
    { abbr: 'Neogene',    start: 23,  end: 2.6, color: '#3A8A78' },
    { abbr: 'Quaternary',  start: 2.6, end: 0,   color: '#5A78A8' },
  ];
  const eraSegs = ERAS.map(e => {
    const w = ((e.start - e.end) / TOTAL_MA * 100).toFixed(2);
    return `<div style="flex:${w};background:${e.color}"></div>`;
  }).join('');
  const eraLabels = ERAS.map(e => {
      const w  = ((e.start - e.end) / TOTAL_MA * 100);
      const left = ((TOTAL_MA - e.start) / TOTAL_MA * 100).toFixed(2);
      const center = (parseFloat(left) + w / 2).toFixed(2);
      const abbr = w < 6 ? 'Q' : e.abbr;
      return `<span class="ls-epoch-label" style="left:${center}%">${abbr}</span>`;
  }).join('');

  const startMa  = Math.min(animal.appeared, TOTAL_MA);
  const endMa    = parseEndMa(animal);
  const startPct = ((TOTAL_MA - startMa) / TOTAL_MA * 100).toFixed(1);
  const endPct   = ((TOTAL_MA - endMa)   / TOTAL_MA * 100).toFixed(1);
  const widthPct = (parseFloat(endPct) - parseFloat(startPct)).toFixed(1);

  return `
    <div class="feedback-info">
      <div class="feedback-info-item full">
        <div class="fi-row"><span class="fi-main">${animal.period.replace(/\s*\([^)]*\)/, '').trim()}</span></div>
        <div class="fi-sub">First appeared: ~${animal.appeared} Ma ago</div>
        ${extinctBadge}
        <div class="lifespan-bar-wrap">
          <div class="lifespan-stage">
            <div class="lifespan-float">
              <div class="lifespan-fill" style="left:${startPct}%;width:${widthPct}%"></div>
              <div class="lifespan-marker" style="left:${startPct}%"></div>
              ${animal.extinct ? `<div class="lifespan-marker" style="left:${endPct}%"></div>` : ''}
            </div>
            <div class="lifespan-track">${eraSegs}</div>
          </div>
          <div class="lifespan-epoch-row">${eraLabels}</div>
        </div>
      </div>
      <div class="feedback-info-item">
        <div class="fi-big">${animal.length}m</div>
        <div class="fi-sub">${ft}ft</div>
        <div class="sizometer">${pips}<span class="sizo-label">${sizeLabel}</span></div>
      </div>
      <div class="feedback-info-item fi-centered">
        <div class="fi-big">${animal.speed} km/h</div>
        <div class="fi-sub">${mph} mph</div>
      </div>
      <div class="feedback-info-item fi-centered">
        <div class="fi-big">${animal.diet}</div>
      </div>
      <div class="feedback-info-item geo-item fi-centered">
        <div class="geo-text"><span class="fi-geo">${animal.geo}</span></div>
        <div class="fi-globes">${globes}</div>
      </div>
    </div>`;
}

function showAnswerView(correct, pts, q) {
  const area = document.getElementById('question-area');
  const isBattle = q.type === 'faster';
  const infoAnimal = isBattle ? q.faster : q.correct;
  const correctName = infoAnimal.name;

  const imgSrc = imageCache[infoAnimal.wiki];
  const imgHTML = imgSrc
    ? `<div class="answer-img-wrap">
        <img src="${imgSrc}" alt="${infoAnimal.name}" class="answer-dino-img"/>
        <button class="report-img-btn" onclick="reportImage('${infoAnimal.name.replace(/'/g,"\\'")}', '${imgSrc}', this)">⚑ Report image</button>
       </div>`
    : '';

  let factText = '';
  const cached = factCache[infoAnimal.wiki] || { short: '', full: '' };
  if (cached.short) {
    const more = cached.full
      ? `<details class="answer-fact-more"><summary>Read more</summary><p>${cached.full}</p></details>`
      : '';
    factText = `<p class="answer-fact">${cached.short}</p>${more}`;
  }

  // Battle-type extra feedback
  if (q.type === 'faster') {
    const fast = q.faster;
    const slow = fast.name === q.a.name ? q.b : q.a;
    factText += `<p class="answer-fact">
      ${fast.name}: ${fast.speed} km/h (${Math.round(fast.speed * 0.621)} mph) &nbsp;·&nbsp;
      ${slow.name}: ${slow.speed} km/h (${Math.round(slow.speed * 0.621)} mph)
    </p>`;
  }

  area.innerHTML = `
    <div class="answer-view ${correct ? 'correct' : 'wrong'}">
      <div class="answer-header">
        <span class="answer-icon">${correct ? '✅' : '❌'}</span>
        <span class="answer-label">${correct ? 'Correct!' : 'Nope!'}</span>
        ${correct
          ? `<span class="answer-pts">+${pts} pts</span>`
          : `<span class="answer-name">${correctName}</span>`}
      </div>
      ${imgHTML}
      ${factText}
      ${animalInfoHTML(infoAnimal)}
      <div class="answer-tap-hint">tap or press space to continue</div>
    </div>`;
}

async function reportImage(dinoName, imgUrl, btnEl) {
  btnEl.disabled = true;
  btnEl.style.display = 'none';

  const report = { dino: dinoName, img: imgUrl, date: new Date().toISOString() };

  // Always save locally
  const stored = JSON.parse(localStorage.getItem('cenozoiquest_reports') || '[]');
  stored.push(report);
  localStorage.setItem('cenozoiquest_reports', JSON.stringify(stored));

  // Send to Discord webhook if configured
  const webhook = (typeof CONFIG !== 'undefined') && CONFIG.discordWebhook;
  if (webhook) {
    try {
      await fetch(webhook, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: `🚩 **Bad image report**\n**Dino:** ${dinoName}\n**Image:** ${imgUrl}`,
        }),
      });
    } catch { /* non-critical */ }
  }

  // Show thank-you modal (does not advance the game)
  const overlay = document.createElement('div');
  overlay.className = 'report-modal-overlay';
  overlay.innerHTML = `
    <div class="report-modal">
      <div class="report-modal-icon">🚩</div>
      <div class="report-modal-title">Thanks for the report!</div>
      <div class="report-modal-body">We've logged the image for <strong>${dinoName}</strong> and will review it.</div>
      <button class="report-modal-btn">Got it</button>
    </div>`;
  overlay.querySelector('.report-modal-btn').addEventListener('click', () => overlay.remove());
  document.body.appendChild(overlay);
}

function waitForAnswerDismiss() {
  return new Promise(resolve => {
    const area = document.getElementById('question-area');
    function onClick(e) {
      if (e.target.closest('.answer-fact-more')) return;
      if (e.target.closest('.report-img-btn')) return;
      area.removeEventListener('click', onClick);
      resolve();
    }
    // Delay so the click that triggered the answer doesn't immediately dismiss
    setTimeout(() => area.addEventListener('click', onClick), 0);
  });
}

async function showHighScores() {
  showScreen('screen-highscores');
  const tbody = document.getElementById('scores-table-body');
  tbody.innerHTML = '<tr><td colspan="2" style="text-align:center;opacity:.5">Loading...</td></tr>';
  document.getElementById('hs-mode-label').textContent = 'Global Leaderboard';

  const scores = await getTopScores(10);
  tbody.innerHTML = '';
  if (scores.length === 0) {
    tbody.innerHTML = '<tr><td colspan="2" style="text-align:center">No scores yet!</td></tr>';
  } else {
    scores.forEach((s, i) => {
      const tr = document.createElement('tr');
      if (i === 0) tr.classList.add('gold');
      if (i === 1) tr.classList.add('silver');
      if (i === 2) tr.classList.add('bronze');
      tr.innerHTML = `<td>${i + 1}. ${s.initials}</td><td>${s.score}</td>`;
      tbody.appendChild(tr);
    });
  }
}

// ── Screens ───────────────────────────────────────────────────────────────────

function showScreen(id) {
  document.querySelectorAll('.screen').forEach(s => s.classList.remove('active'));
  document.getElementById(id).classList.add('active');
  if (id === 'screen-title') {
    startTitleDinos();
    const session = loadSession();
    const btnContinue = document.getElementById('btn-continue');
    if (session && session.level > 1) {
      btnContinue.textContent = `▶ Continue — Level ${session.level}`;
      btnContinue.style.display = '';
    } else {
      btnContinue.style.display = 'none';
    }
  } else {
    stopTitleDinos();
  }
}

function setLoadingMessage(msg) {
  document.getElementById('loading-msg').textContent = msg;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function delay(ms) { return new Promise(r => setTimeout(r, ms)); }
function capitalize(s) { return s.charAt(0).toUpperCase() + s.slice(1); }
function modeName(m) {
  return { 'name-match': 'Name Match', 'pic-match': 'Picture Match', 'faster': 'Who\'s Faster' }[m] || m;
}

// ── Title screen dino bouncer ─────────────────────────────────────────────────

let dinoBouncerRaf = null;

function startTitleDinos() {
  const screen = document.getElementById('screen-title');
  const els    = [...screen.querySelectorAll('.title-dino')];
  const SIZE   = 52; // px — approximate rendered emoji size
  const SPEED  = 1.8;

  // place each dino and give it a random starting velocity
  const dinos = els.map((el, i) => {
    const w = window.innerWidth;
    const h = window.innerHeight;
    // Start in corners, well away from the centered UI
    const corners = [
      { x: SIZE, y: SIZE },
      { x: w - SIZE * 2, y: SIZE },
      { x: SIZE, y: h - SIZE * 2 },
      { x: w - SIZE * 2, y: h - SIZE * 2 },
    ];
    const { x, y } = corners[i % corners.length];
    let vx = (Math.random() < 0.5 ? 1 : -1) * (SPEED * 0.7 + Math.random() * SPEED * 0.6);
    let vy = (Math.random() < 0.5 ? 1 : -1) * (SPEED * 0.7 + Math.random() * SPEED * 0.6);
    el.style.left = x + 'px';
    el.style.top  = y + 'px';
    return { el, x, y, vx, vy };
  });

  // get obstacle rects (title text, subtitle, buttons) relative to screen
  function obstacles() {
    const sr = screen.getBoundingClientRect();
    return [...screen.querySelectorAll('.game-title,.game-subtitle,.big-btn')]
      .map(el => {
        const r = el.getBoundingClientRect();
        return { l: r.left - sr.left - 4, t: r.top - sr.top - 4,
                 r: r.right - sr.left + 4, b: r.bottom - sr.top + 4 };
      });
  }

  function tick() {
    const W   = window.innerWidth;
    const H   = window.innerHeight;
    const obs = obstacles();

    for (const d of dinos) {
      d.x += d.vx;
      d.y += d.vy;

      // wall bounce
      if (d.x < 0)        { d.x = 0;        d.vx =  Math.abs(d.vx); }
      if (d.x + SIZE > W) { d.x = W - SIZE;  d.vx = -Math.abs(d.vx); }
      if (d.y < 0)        { d.y = 0;         d.vy =  Math.abs(d.vy); }
      if (d.y + SIZE > H) { d.y = H - SIZE;  d.vy = -Math.abs(d.vy); }

      // obstacle bounce
      const cx = d.x + SIZE / 2, cy = d.y + SIZE / 2;
      for (const o of obs) {
        if (cx > o.l && cx < o.r && cy > o.t && cy < o.b) {
          const dl = Math.abs(cx - o.l), dr = Math.abs(cx - o.r);
          const dt = Math.abs(cy - o.t), db = Math.abs(cy - o.b);
          const m  = Math.min(dl, dr, dt, db);
          if (m === dl || m === dr) d.vx = -d.vx;
          else                      d.vy = -d.vy;
        }
      }

      d.el.style.left = d.x + 'px';
      d.el.style.top  = d.y + 'px';
    }

    // dino–dino bounce
    for (let i = 0; i < dinos.length; i++) {
      for (let j = i + 1; j < dinos.length; j++) {
        const a = dinos[i], b = dinos[j];
        const dx = (b.x + SIZE / 2) - (a.x + SIZE / 2);
        const dy = (b.y + SIZE / 2) - (a.y + SIZE / 2);
        const dist = Math.hypot(dx, dy);
        if (dist < SIZE && dist > 0) {
          const nx = dx / dist, ny = dy / dist;
          // reflect velocities along collision normal
          const dvx = a.vx - b.vx, dvy = a.vy - b.vy;
          const dot  = dvx * nx + dvy * ny;
          a.vx -= dot * nx;  a.vy -= dot * ny;
          b.vx += dot * nx;  b.vy += dot * ny;
          // push apart
          const overlap = SIZE - dist;
          a.x -= nx * overlap / 2;  a.y -= ny * overlap / 2;
          b.x += nx * overlap / 2;  b.y += ny * overlap / 2;
        }
      }
    }

    dinoBouncerRaf = requestAnimationFrame(tick);
  }

  cancelAnimationFrame(dinoBouncerRaf);
  tick();
}

function stopTitleDinos() {
  cancelAnimationFrame(dinoBouncerRaf);
  dinoBouncerRaf = null;
}

// ── Init ──────────────────────────────────────────────────────────────────────

document.addEventListener('keydown', e => {
  if (document.getElementById('screen-title').classList.contains('active')) {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      document.getElementById('btn-play').click();
    }
    return;
  }

  if (document.getElementById('screen-map').classList.contains('active')) {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      const btn = document.getElementById('btn-map-continue');
      if (btn.style.pointerEvents !== 'none') btn.click();
    }
    return;
  }

  if (!document.getElementById('screen-game').classList.contains('active')) return;

  // Advance from answer view
  if (state.answeredThisRound) {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      document.getElementById('question-area').click();
    }
    return;
  }

  const buttons = getOptionButtons();
  if (!buttons.length) return;

  const dirMap = { ArrowRight: 'right', ArrowLeft: 'left', ArrowDown: 'down', ArrowUp: 'up' };
  const dir = dirMap[e.key];

  if (dir) {
    e.preventDefault();
    if (focusedOptionIndex === -1) {
      // Entry: "back" directions jiggle; "forward" directions enter at index 0
      const backDir = getGridCols() === 1 ? (dir === 'up') : (dir === 'left' || dir === 'up');
      if (backDir) {
        jiggleKbCursor();
      } else {
        focusedOptionIndex = 0;
        applyKeyboardFocus(buttons);
      }
    } else {
      const next = gridMove(focusedOptionIndex, dir, buttons.length);
      if (next !== null) {
        focusedOptionIndex = next;
        applyKeyboardFocus(buttons);
      } else {
        jiggleFocused(buttons);
      }
    }
  } else if (e.key === ' ' || e.key === 'Enter') {
    e.preventDefault();
    if (focusedOptionIndex === -1) {
      jiggleKbCursor();
    } else if (focusedOptionIndex < buttons.length) {
      buttons[focusedOptionIndex].click();
    }
  }
});

document.addEventListener('DOMContentLoaded', () => {
  showScreen('screen-title');

  // Title screen
  document.getElementById('btn-continue').addEventListener('click', resumeGame);
  document.getElementById('btn-play').addEventListener('click', () => { clearSession(); startGame(); });
  document.getElementById('btn-scores-title').addEventListener('click', () => {
    showHighScores();
    document.getElementById('hs-back-btn').onclick = () => showScreen('screen-title');
  });

  // In-game
  document.getElementById('btn-quit-game').addEventListener('click', () => {
    if (confirm('Quit this game?')) { clearSession(); showScreen('screen-title'); }
  });

  // Game over
  document.getElementById('btn-submit-score').addEventListener('click', submitScore);
  document.getElementById('btn-main-menu').addEventListener('click', () => showScreen('screen-title'));

  // Initials input: uppercase only, max 3
  const inp = document.getElementById('initials-input');
  inp.addEventListener('input', () => {
    inp.value = inp.value.toUpperCase().replace(/[^A-Z]/g, '').slice(0, 3);
  });
  inp.addEventListener('keydown', e => {
    if (e.key === 'Enter') submitScore();
  });

  // High scores back
  document.getElementById('hs-back-btn').addEventListener('click', () => showScreen('screen-title'));
});
