#!/usr/bin/env python3
"""Admin server for editing dino data. Run via `make admin`."""

import json
import re
import os
import sys
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.parse import urlparse

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DINO_DATA_PATH = os.path.join(BASE_DIR, 'js', 'dino-data.js')
PORT = 8081


def load_dino_data():
    with open(DINO_DATA_PATH, 'r', encoding='utf-8') as f:
        content = f.read()
    match = re.search(r'const DINO_DATA\s*=\s*(\{.*\})\s*;', content, re.DOTALL)
    if not match:
        raise ValueError("Could not parse dino-data.js")
    return json.loads(match.group(1))


def save_dino_data(data):
    header = (
        '// Auto-generated by scripts/fetch-dino-data.py \u2014 do not edit manually.\n'
        '// Run `make fetch-data` to refresh.\n'
    )
    json_str = json.dumps(data, indent=2, ensure_ascii=False)
    content = f'{header}const DINO_DATA = {json_str};\n'
    with open(DINO_DATA_PATH, 'w', encoding='utf-8') as f:
        f.write(content)


class AdminHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=BASE_DIR, **kwargs)

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path == '/api/update':
            length = int(self.headers.get('Content-Length', 0))
            body = self.rfile.read(length)
            try:
                update = json.loads(body)
            except json.JSONDecodeError:
                self.send_error(400, 'Invalid JSON')
                return

            wiki = update.get('wiki')
            if not wiki:
                self.send_error(400, 'Missing wiki key')
                return

            try:
                data = load_dino_data()
                if wiki not in data:
                    data[wiki] = {}
                for field in ('img', 'short', 'full'):
                    if field in update:
                        data[wiki][field] = update[field]
                save_dino_data(data)
            except Exception as e:
                self.send_response(500)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({'ok': False, 'error': str(e)}).encode())
                return

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(b'{"ok": true}')
        else:
            self.send_error(404)

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, GET, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def log_message(self, fmt, *args):
        print(f'  {fmt % args}')


if __name__ == '__main__':
    server = HTTPServer(('', PORT), AdminHandler)
    print(f'Admin server → http://localhost:{PORT}/admin.html')
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print('\nStopped.')
        sys.exit(0)
