#!/usr/bin/env python3
"""Admin server for Moon Game level designer. Run via `make moon-admin`."""

import json
import os
import sys
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.parse import urlparse

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEVELS_PATH = os.path.join(BASE_DIR, 'moon-game', 'js', 'levels.js')
PORT = 8083


def build_levels_js(levels, globals_data):
    json_levels  = json.dumps(levels,       indent=2, ensure_ascii=False)
    json_globals = json.dumps(globals_data, indent=2, ensure_ascii=False)
    return f"""\
// Level data. Positions use 0-1 fractions of canvas size (400x700).
// Sizes (length, radius, size) are in absolute pixels at that canvas resolution.
// Auto-generated by admin.html — do not edit by hand.

// ── Global physics (apply to all levels) ────────────────────────────────────

const DEFAULT_GLOBALS = {json_globals};

function getGlobals() {{
  return {{ ...DEFAULT_GLOBALS }};
}}

// ── Level definitions ────────────────────────────────────────────────────────

const DEFAULT_LEVELS = {json_levels};

function getLevels() {{
  return JSON.parse(JSON.stringify(DEFAULT_LEVELS));
}}

function getLevel(id) {{
  return getLevels().find(l => l.id === id) || getLevels()[0];
}}

// saveLevels / saveGlobals are no-ops — persistence goes through the server.
function saveLevels() {{}}
function saveGlobals() {{}}
"""


class AdminHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=BASE_DIR, **kwargs)

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path == '/api/save-levels':
            length = int(self.headers.get('Content-Length', 0))
            body = self.rfile.read(length)
            try:
                data = json.loads(body)
                levels  = data['levels']
                globals_data = data['globals']
            except (json.JSONDecodeError, KeyError) as e:
                self.send_error(400, f'Bad request: {e}')
                return

            try:
                content = build_levels_js(levels, globals_data)
                with open(LEVELS_PATH, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f'  Saved {len(levels)} level(s) → {LEVELS_PATH}')
            except Exception as e:
                self.send_response(500)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({'ok': False, 'error': str(e)}).encode())
                return

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(b'{"ok": true}')
        else:
            self.send_error(404)

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, GET, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def log_message(self, fmt, *args):
        print(f'  {fmt % args}')


if __name__ == '__main__':
    server = HTTPServer(('', PORT), AdminHandler)
    print(f'Moon admin server → http://localhost:{PORT}/moon-game/admin.html')
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print('\nStopped.')
        sys.exit(0)
