#!/usr/bin/env python3
"""
Fetch dino facts and image URLs from Wikipedia and write js/dino-data.js.
Run via: make fetch-data
"""

import json
import time
import urllib.request
import urllib.parse
import re
import sys
import os

WIKI_TITLES = [
    # Level 1
    "Tyrannosaurus", "Triceratops", "Stegosaurus", "Brachiosaurus",
    "Velociraptor", "Ankylosaurus", "Diplodocus", "Spinosaurus",
    "Pteranodon", "Apatosaurus", "Allosaurus", "Iguanodon",
    # Level 2
    "Parasaurolophus", "Pachycephalosaurus", "Carnotaurus", "Dilophosaurus",
    "Gallimimus", "Mosasaurus", "Archaeopteryx", "Edmontosaurus",
    "Deinonychus", "Coelophysis", "Troodon", "Utahraptor",
    "Corythosaurus", "Plateosaurus",
    # Level 3
    "Baryonyx", "Ceratosaurus", "Maiasaura", "Oviraptor",
    "Carcharodontosaurus", "Suchomimus", "Kentrosaurus", "Protoceratops",
    "Camarasaurus", "Camptosaurus", "Ouranosaurus", "Psittacosaurus",
    "Saurolophus", "Megaraptor", "Concavenator",
    # Level 4
    "Styracosaurus", "Therizinosaurus", "Gorgosaurus", "Amargasaurus",
    "Euoplocephalus", "Pachyrhinosaurus", "Lambeosaurus", "Albertosaurus",
    "Pentaceratops", "Anchiceratops", "Irritator_(dinosaur)",
    "Scelidosaurus", "Tsintaosaurus",
    # Level 5
    "Argentinosaurus", "Quetzalcoatlus", "Microraptor", "Giganotosaurus",
    "Eoraptor", "Sauroposeidon", "Sinosauropteryx", "Herrerasaurus",
    "Dracorex", "Nothronychus", "Magyarosaurus", "Abrictosaurus",
    "Yinlong", "Limusaurus",
]

HEADERS = {'User-Agent': 'DinoQuest/1.0 (educational game; contact via github)'}


def fetch_summary(title):
    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{urllib.parse.quote(title)}"
    try:
        req = urllib.request.Request(url, headers=HEADERS)
        with urllib.request.urlopen(req, timeout=15) as r:
            data = json.loads(r.read())
        extract = data.get('extract', '')
        m = re.match(r'[^.!?]*[.!?]', extract)
        short = m.group(0).strip() if m else extract[:200].strip()
        full = extract[len(m.group(0)):].strip() if m else ''
        return short, full
    except Exception as e:
        print(f"  ⚠ summary failed for {title}: {e}", file=sys.stderr)
        return '', ''


def fetch_image(title):
    params = urllib.parse.urlencode({
        'action': 'query',
        'titles': title,
        'prop': 'pageimages',
        'format': 'json',
        'pithumbsize': 600,
    })
    url = f"https://en.wikipedia.org/w/api.php?{params}"
    try:
        req = urllib.request.Request(url, headers=HEADERS)
        with urllib.request.urlopen(req, timeout=15) as r:
            data = json.loads(r.read())
        page = list(data['query']['pages'].values())[0]
        return page.get('thumbnail', {}).get('source', '')
    except Exception as e:
        print(f"  ⚠ image failed for {title}: {e}", file=sys.stderr)
        return ''


results = {}
total = len(WIKI_TITLES)

for i, title in enumerate(WIKI_TITLES, 1):
    print(f"[{i}/{total}] {title}")
    short, full = fetch_summary(title)
    time.sleep(0.4)
    img = fetch_image(title)
    time.sleep(0.4)
    results[title] = {'img': img, 'short': short, 'full': full}
    if not img:
        print(f"        (no image)")
    if not short:
        print(f"        (no fact)")

# Write output relative to this script's location
out_path = os.path.join(os.path.dirname(__file__), '..', 'js', 'dino-data.js')
out_path = os.path.normpath(out_path)

with open(out_path, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by scripts/fetch-dino-data.py — do not edit manually.\n')
    f.write('// Run `make fetch-data` to refresh.\n')
    f.write('const DINO_DATA = ')
    json.dump(results, f, indent=2, ensure_ascii=False)
    f.write(';\n')

ok = sum(1 for v in results.values() if v['img'])
print(f"\n✓ Done! {ok}/{total} images, wrote {out_path}")
