#!/usr/bin/env python3
"""
Fetch or re-fetch a single dino and merge it into js/dino-data.js.
Usage: make fetch-one DINO="Irritator"
   or: python3 scripts/fetch-one.py "Irritator"
"""

import json, re, sys, os, time
import urllib.request, urllib.parse, ssl

if len(sys.argv) < 2:
    print("Usage: python3 scripts/fetch-one.py <WikiTitle>")
    sys.exit(1)

title = sys.argv[1]

SSL_CTX = ssl.create_default_context()
SSL_CTX.check_hostname = False
SSL_CTX.verify_mode = ssl.CERT_NONE

HEADERS = {'User-Agent': 'DinoQuest/1.0 (educational game; contact via github)'}

def fetch_summary(t):
    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{urllib.parse.quote(t)}"
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=15, context=SSL_CTX) as r:
        data = json.loads(r.read())
    extract = data.get('extract', '')
    m = re.search(r'.+?[.!?](?=\s+[A-Z]|\s*$)', extract, re.DOTALL)
    short = m.group(0).strip() if m else extract[:200].strip()
    full  = extract[len(m.group(0)):].strip() if m else ''
    return short, full

def fetch_image(t):
    params = urllib.parse.urlencode({
        'action': 'query', 'titles': t, 'prop': 'pageimages',
        'format': 'json', 'pithumbsize': 600,
    })
    url = f"https://en.wikipedia.org/w/api.php?{params}"
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=15, context=SSL_CTX) as r:
        data = json.loads(r.read())
    page = list(data['query']['pages'].values())[0]
    return page.get('thumbnail', {}).get('source', '')

out_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'js', 'dino-data.js'))

# Load existing data
existing = {}
if os.path.exists(out_path):
    content = open(out_path).read()
    m = re.search(r'const DINO_DATA\s*=\s*(\{[\s\S]*\});', content)
    if m:
        existing = json.loads(m.group(1))

print(f"Fetching: {title}")
try:
    short, full = fetch_summary(title)
    print(f"  fact: {short[:60]}...")
except Exception as e:
    print(f"  ⚠ summary failed: {e}")
    short, full = '', ''

time.sleep(1)

try:
    img = fetch_image(title)
    print(f"  img:  {img[:60]}..." if img else "  ⚠ no image found")
except Exception as e:
    print(f"  ⚠ image failed: {e}")
    img = ''

existing[title] = {'img': img, 'short': short, 'full': full}

with open(out_path, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by scripts/fetch-dino-data.py — do not edit manually.\n')
    f.write('// Run `make fetch-data` to refresh.\n')
    f.write('const DINO_DATA = ')
    json.dump(existing, f, indent=2, ensure_ascii=False)
    f.write(';\n')

print(f"✓ Updated {out_path}")
