#!/usr/bin/env python3
"""
Re-fetch full descriptions for animals with empty 'full' fields,
using the Wikipedia extracts API to get the complete intro section.
"""

import json, re, sys, os, time
import urllib.request, urllib.parse, ssl

SSL_CTX = ssl.create_default_context()
SSL_CTX.check_hostname = False
SSL_CTX.verify_mode = ssl.CERT_NONE

HEADERS = {'User-Agent': 'AfterImpact/1.0 (educational game; contact via github)'}

def fetch_extract(title):
    params = urllib.parse.urlencode({
        'action': 'query',
        'titles': title,
        'prop': 'extracts',
        'exintro': 1,
        'explaintext': 1,
        'format': 'json',
    })
    url = f"https://en.wikipedia.org/w/api.php?{params}"
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=15, context=SSL_CTX) as r:
        data = json.loads(r.read())
    page = list(data['query']['pages'].values())[0]
    return page.get('extract', '').strip()

out_path = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'animal-game', 'js', 'animal-data.js'))

content = open(out_path).read()
m = re.search(r'const ANIMAL_DATA\s*=\s*(\{[\s\S]*\});', content)
existing = json.loads(m.group(1))

targets = [k for k, v in existing.items() if not v.get('full', '').strip()]
print(f"Re-fetching {len(targets)} entries with no full description...\n")

for title in targets:
    print(f"  {title}")
    try:
        extract = fetch_extract(title)
        if extract:
            # Split into short (first sentence) and full (the rest)
            sm = re.search(r'.+?[.!?](?=\s+[A-Z]|\s*$)', extract, re.DOTALL)
            short = sm.group(0).strip() if sm else extract[:200].strip()
            full  = extract[len(sm.group(0)):].strip() if sm else ''
            existing[title]['short'] = short
            existing[title]['full']  = full
            preview = full[:80] if full else '(still empty)'
            print(f"    short: {short[:60]}...")
            print(f"    full:  {preview}...")
        else:
            print(f"    ⚠ no extract returned")
    except Exception as e:
        print(f"    ⚠ failed: {e}")
    time.sleep(1.5)

with open(out_path, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by scripts/fetch-animal-data.py — do not edit manually.\n')
    f.write('// Run `make fetch-animal-data` to refresh.\n')
    f.write('const ANIMAL_DATA = ')
    json.dump(existing, f, indent=2, ensure_ascii=False)
    f.write(';\n')

print(f"\n✓ Done — updated {out_path}")
