#!/usr/bin/env python3
"""
Merge prehistoric-wiki data into existing dino-data.js and dinos.js:
  - dino-data.js: replace img URLs with prehistoric-wiki ones (where available)
  - dinos.js:     fill length=0 entries with lengths from prehistoric-wiki

Descriptions (short/full) in dino-data.js are left untouched.

Usage:
  python3 scripts/merge-prehistoric.py
  make merge-prehistoric
"""

import json, re, os

ROOT         = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
DINO_DATA_JS = os.path.join(ROOT, 'js', 'dino-data.js')
PREHISTORIC  = os.path.join(ROOT, 'js', 'prehistoric-data.js')
DINOS_JS     = os.path.join(ROOT, 'js', 'dinos.js')

# ── Load prehistoric-data.js ──────────────────────────────────────────────────

content = open(PREHISTORIC, encoding='utf-8').read()
m = re.search(r'const PREHISTORIC_DATA\s*=\s*(\{[\s\S]*\});', content)
prehistoric = json.loads(m.group(1))

# ── 1. Update images in dino-data.js ─────────────────────────────────────────

dino_content = open(DINO_DATA_JS, encoding='utf-8').read()
m = re.search(r'const DINO_DATA\s*=\s*(\{[\s\S]*\});', dino_content)
dino_data = json.loads(m.group(1))

img_updated = 0
for wiki, entry in prehistoric.items():
    if entry.get('img') and wiki in dino_data:
        dino_data[wiki]['img'] = entry['img']
        img_updated += 1
    elif entry.get('img') and wiki not in dino_data:
        # dino exists in prehistoric but not in dino-data.js — add a stub
        dino_data[wiki] = {
            'img':   entry['img'],
            'short': entry.get('short', ''),
            'full':  entry.get('full', ''),
        }
        img_updated += 1

with open(DINO_DATA_JS, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by scripts/fetch-dino-data.py — do not edit manually.\n')
    f.write('// Run `make fetch-data` to refresh.\n')
    f.write('const DINO_DATA = ')
    json.dump(dino_data, f, indent=2, ensure_ascii=False)
    f.write(';\n')

print(f'✓ Updated {img_updated} image(s) in dino-data.js')

# ── 2. Fill length=0 in dinos.js ─────────────────────────────────────────────

dinos_content = open(DINOS_JS, encoding='utf-8').read()
updated = dinos_content
len_updated = 0

entry_pat = re.compile(
    r'(\{[^}]*name:\s*"([^"]+)"[^}]*wiki:\s*"([^"]+)"[^}]*length:\s*(0(?:\.0+)?)\b[^}]*\})',
    re.DOTALL
)

for m in entry_pat.finditer(dinos_content):
    wiki  = m.group(3)
    pdata = prehistoric.get(wiki, {})
    length = pdata.get('length')
    if length is None:
        continue
    old_block = m.group(1)
    new_block = re.sub(r'(length:\s*)0\b', f'\\g<1>{length}', old_block, count=1)
    updated   = updated.replace(old_block, new_block, 1)
    len_updated += 1
    print(f'  length {wiki}: {length}m')

with open(DINOS_JS, 'w', encoding='utf-8') as f:
    f.write(updated)

print(f'✓ Updated {len_updated} length(s) in dinos.js')
